// Code generated by ent, DO NOT EDIT.

package userradiofavorite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userradiofavorite type in the database.
	Label = "user_radio_favorite"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStationID holds the string denoting the station_id field in the database.
	FieldStationID = "station_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCodec holds the string denoting the codec field in the database.
	FieldCodec = "codec"
	// FieldBitrate holds the string denoting the bitrate field in the database.
	FieldBitrate = "bitrate"
	// FieldHomepage holds the string denoting the homepage field in the database.
	FieldHomepage = "homepage"
	// FieldFavicon holds the string denoting the favicon field in the database.
	FieldFavicon = "favicon"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userradiofavorite in the database.
	Table = "user_radio_favorites"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_radio_favorites"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_radio_favorites"
)

// Columns holds all SQL columns for userradiofavorite fields.
var Columns = []string{
	FieldID,
	FieldStationID,
	FieldName,
	FieldURL,
	FieldSourceURL,
	FieldGroupName,
	FieldCountry,
	FieldTags,
	FieldCodec,
	FieldBitrate,
	FieldHomepage,
	FieldFavicon,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_radio_favorites"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_radio_favorites",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// StationIDValidator is a validator for the "station_id" field. It is called by the builders before save.
	StationIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultSourceURL holds the default value on creation for the "source_url" field.
	DefaultSourceURL string
	// DefaultGroupName holds the default value on creation for the "group_name" field.
	DefaultGroupName string
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags string
	// DefaultCodec holds the default value on creation for the "codec" field.
	DefaultCodec string
	// DefaultBitrate holds the default value on creation for the "bitrate" field.
	DefaultBitrate int
	// DefaultHomepage holds the default value on creation for the "homepage" field.
	DefaultHomepage string
	// DefaultFavicon holds the default value on creation for the "favicon" field.
	DefaultFavicon string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserRadioFavorite queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStationID orders the results by the station_id field.
func ByStationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStationID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByCodec orders the results by the codec field.
func ByCodec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodec, opts...).ToFunc()
}

// ByBitrate orders the results by the bitrate field.
func ByBitrate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBitrate, opts...).ToFunc()
}

// ByHomepage orders the results by the homepage field.
func ByHomepage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomepage, opts...).ToFunc()
}

// ByFavicon orders the results by the favicon field.
func ByFavicon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFavicon, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
