// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/album"
	"lark/backend/ent/artist"
	"lark/backend/ent/predicate"
	"lark/backend/ent/song"
	"lark/backend/ent/useralbumfavorite"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlbumUpdate is the builder for updating Album entities.
type AlbumUpdate struct {
	config
	hooks    []Hook
	mutation *AlbumMutation
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdate) Where(ps ...predicate.Album) *AlbumUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AlbumUpdate) SetTitle(v string) *AlbumUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableTitle(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *AlbumUpdate) SetAlbumArtist(v string) *AlbumUpdate {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableAlbumArtist(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetCoverPath sets the "cover_path" field.
func (_u *AlbumUpdate) SetCoverPath(v string) *AlbumUpdate {
	_u.mutation.SetCoverPath(v)
	return _u
}

// SetNillableCoverPath sets the "cover_path" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableCoverPath(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetCoverPath(*v)
	}
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *AlbumUpdate) SetFavorite(v bool) *AlbumUpdate {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableFavorite(v *bool) *AlbumUpdate {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AlbumUpdate) SetCreatedAt(v time.Time) *AlbumUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableCreatedAt(v *time.Time) *AlbumUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlbumUpdate) SetUpdatedAt(v time.Time) *AlbumUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *AlbumUpdate) SetArtistID(id int) *AlbumUpdate {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *AlbumUpdate) SetNillableArtistID(id *int) *AlbumUpdate {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) SetArtist(v *Artist) *AlbumUpdate {
	return _u.SetArtistID(v.ID)
}

// AddSongIDs adds the "songs" edge to the Song entity by IDs.
func (_u *AlbumUpdate) AddSongIDs(ids ...int) *AlbumUpdate {
	_u.mutation.AddSongIDs(ids...)
	return _u
}

// AddSongs adds the "songs" edges to the Song entity.
func (_u *AlbumUpdate) AddSongs(v ...*Song) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSongIDs(ids...)
}

// AddUserFavoriteIDs adds the "user_favorites" edge to the UserAlbumFavorite entity by IDs.
func (_u *AlbumUpdate) AddUserFavoriteIDs(ids ...int) *AlbumUpdate {
	_u.mutation.AddUserFavoriteIDs(ids...)
	return _u
}

// AddUserFavorites adds the "user_favorites" edges to the UserAlbumFavorite entity.
func (_u *AlbumUpdate) AddUserFavorites(v ...*UserAlbumFavorite) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserFavoriteIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdate) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) ClearArtist() *AlbumUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// ClearSongs clears all "songs" edges to the Song entity.
func (_u *AlbumUpdate) ClearSongs() *AlbumUpdate {
	_u.mutation.ClearSongs()
	return _u
}

// RemoveSongIDs removes the "songs" edge to Song entities by IDs.
func (_u *AlbumUpdate) RemoveSongIDs(ids ...int) *AlbumUpdate {
	_u.mutation.RemoveSongIDs(ids...)
	return _u
}

// RemoveSongs removes "songs" edges to Song entities.
func (_u *AlbumUpdate) RemoveSongs(v ...*Song) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSongIDs(ids...)
}

// ClearUserFavorites clears all "user_favorites" edges to the UserAlbumFavorite entity.
func (_u *AlbumUpdate) ClearUserFavorites() *AlbumUpdate {
	_u.mutation.ClearUserFavorites()
	return _u
}

// RemoveUserFavoriteIDs removes the "user_favorites" edge to UserAlbumFavorite entities by IDs.
func (_u *AlbumUpdate) RemoveUserFavoriteIDs(ids ...int) *AlbumUpdate {
	_u.mutation.RemoveUserFavoriteIDs(ids...)
	return _u
}

// RemoveUserFavorites removes "user_favorites" edges to UserAlbumFavorite entities.
func (_u *AlbumUpdate) RemoveUserFavorites(v ...*UserAlbumFavorite) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserFavoriteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlbumUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlbumUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlbumUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := album.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := album.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Album.title": %w`, err)}
		}
	}
	return nil
}

func (_u *AlbumUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(album.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverPath(); ok {
		_spec.SetField(album.FieldCoverPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(album.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(album.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(album.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSongsIDs(); len(nodes) > 0 && !_u.mutation.SongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserFavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserFavoritesIDs(); len(nodes) > 0 && !_u.mutation.UserFavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserFavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlbumUpdateOne is the builder for updating a single Album entity.
type AlbumUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlbumMutation
}

// SetTitle sets the "title" field.
func (_u *AlbumUpdateOne) SetTitle(v string) *AlbumUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableTitle(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *AlbumUpdateOne) SetAlbumArtist(v string) *AlbumUpdateOne {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableAlbumArtist(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetCoverPath sets the "cover_path" field.
func (_u *AlbumUpdateOne) SetCoverPath(v string) *AlbumUpdateOne {
	_u.mutation.SetCoverPath(v)
	return _u
}

// SetNillableCoverPath sets the "cover_path" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableCoverPath(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetCoverPath(*v)
	}
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *AlbumUpdateOne) SetFavorite(v bool) *AlbumUpdateOne {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableFavorite(v *bool) *AlbumUpdateOne {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AlbumUpdateOne) SetCreatedAt(v time.Time) *AlbumUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableCreatedAt(v *time.Time) *AlbumUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlbumUpdateOne) SetUpdatedAt(v time.Time) *AlbumUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *AlbumUpdateOne) SetArtistID(id int) *AlbumUpdateOne {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableArtistID(id *int) *AlbumUpdateOne {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) SetArtist(v *Artist) *AlbumUpdateOne {
	return _u.SetArtistID(v.ID)
}

// AddSongIDs adds the "songs" edge to the Song entity by IDs.
func (_u *AlbumUpdateOne) AddSongIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.AddSongIDs(ids...)
	return _u
}

// AddSongs adds the "songs" edges to the Song entity.
func (_u *AlbumUpdateOne) AddSongs(v ...*Song) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSongIDs(ids...)
}

// AddUserFavoriteIDs adds the "user_favorites" edge to the UserAlbumFavorite entity by IDs.
func (_u *AlbumUpdateOne) AddUserFavoriteIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.AddUserFavoriteIDs(ids...)
	return _u
}

// AddUserFavorites adds the "user_favorites" edges to the UserAlbumFavorite entity.
func (_u *AlbumUpdateOne) AddUserFavorites(v ...*UserAlbumFavorite) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserFavoriteIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdateOne) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) ClearArtist() *AlbumUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// ClearSongs clears all "songs" edges to the Song entity.
func (_u *AlbumUpdateOne) ClearSongs() *AlbumUpdateOne {
	_u.mutation.ClearSongs()
	return _u
}

// RemoveSongIDs removes the "songs" edge to Song entities by IDs.
func (_u *AlbumUpdateOne) RemoveSongIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.RemoveSongIDs(ids...)
	return _u
}

// RemoveSongs removes "songs" edges to Song entities.
func (_u *AlbumUpdateOne) RemoveSongs(v ...*Song) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSongIDs(ids...)
}

// ClearUserFavorites clears all "user_favorites" edges to the UserAlbumFavorite entity.
func (_u *AlbumUpdateOne) ClearUserFavorites() *AlbumUpdateOne {
	_u.mutation.ClearUserFavorites()
	return _u
}

// RemoveUserFavoriteIDs removes the "user_favorites" edge to UserAlbumFavorite entities by IDs.
func (_u *AlbumUpdateOne) RemoveUserFavoriteIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.RemoveUserFavoriteIDs(ids...)
	return _u
}

// RemoveUserFavorites removes "user_favorites" edges to UserAlbumFavorite entities.
func (_u *AlbumUpdateOne) RemoveUserFavorites(v ...*UserAlbumFavorite) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserFavoriteIDs(ids...)
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdateOne) Where(ps ...predicate.Album) *AlbumUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlbumUpdateOne) Select(field string, fields ...string) *AlbumUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Album entity.
func (_u *AlbumUpdateOne) Save(ctx context.Context) (*Album, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdateOne) SaveX(ctx context.Context) *Album {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlbumUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlbumUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := album.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := album.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Album.title": %w`, err)}
		}
	}
	return nil
}

func (_u *AlbumUpdateOne) sqlSave(ctx context.Context) (_node *Album, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Album.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, album.FieldID)
		for _, f := range fields {
			if !album.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != album.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(album.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverPath(); ok {
		_spec.SetField(album.FieldCoverPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(album.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(album.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(album.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSongsIDs(); len(nodes) > 0 && !_u.mutation.SongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.SongsTable,
			Columns: []string{album.SongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserFavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserFavoritesIDs(); len(nodes) > 0 && !_u.mutation.UserFavoritesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserFavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.UserFavoritesTable,
			Columns: []string{album.UserFavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Album{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
