// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lark/backend/ent/artist"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Artist is the model entity for the Artist schema.
type Artist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArtistQuery when eager-loading is set.
	Edges        ArtistEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArtistEdges holds the relations/edges for other nodes in the graph.
type ArtistEdges struct {
	// Songs holds the value of the songs edge.
	Songs []*Song `json:"songs,omitempty"`
	// Albums holds the value of the albums edge.
	Albums []*Album `json:"albums,omitempty"`
	// UserFavorites holds the value of the user_favorites edge.
	UserFavorites []*UserArtistFavorite `json:"user_favorites,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SongsOrErr returns the Songs value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) SongsOrErr() ([]*Song, error) {
	if e.loadedTypes[0] {
		return e.Songs, nil
	}
	return nil, &NotLoadedError{edge: "songs"}
}

// AlbumsOrErr returns the Albums value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) AlbumsOrErr() ([]*Album, error) {
	if e.loadedTypes[1] {
		return e.Albums, nil
	}
	return nil, &NotLoadedError{edge: "albums"}
}

// UserFavoritesOrErr returns the UserFavorites value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) UserFavoritesOrErr() ([]*UserArtistFavorite, error) {
	if e.loadedTypes[2] {
		return e.UserFavorites, nil
	}
	return nil, &NotLoadedError{edge: "user_favorites"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Artist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case artist.FieldID:
			values[i] = new(sql.NullInt64)
		case artist.FieldName:
			values[i] = new(sql.NullString)
		case artist.FieldCreatedAt, artist.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Artist fields.
func (_m *Artist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case artist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case artist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case artist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case artist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Artist.
// This includes values selected through modifiers, order, etc.
func (_m *Artist) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySongs queries the "songs" edge of the Artist entity.
func (_m *Artist) QuerySongs() *SongQuery {
	return NewArtistClient(_m.config).QuerySongs(_m)
}

// QueryAlbums queries the "albums" edge of the Artist entity.
func (_m *Artist) QueryAlbums() *AlbumQuery {
	return NewArtistClient(_m.config).QueryAlbums(_m)
}

// QueryUserFavorites queries the "user_favorites" edge of the Artist entity.
func (_m *Artist) QueryUserFavorites() *UserArtistFavoriteQuery {
	return NewArtistClient(_m.config).QueryUserFavorites(_m)
}

// Update returns a builder for updating this Artist.
// Note that you need to call Artist.Unwrap() before calling this method if this Artist
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Artist) Update() *ArtistUpdateOne {
	return NewArtistClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Artist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Artist) Unwrap() *Artist {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Artist is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Artist) String() string {
	var builder strings.Builder
	builder.WriteString("Artist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Artists is a parsable slice of Artist.
type Artists []*Artist
