// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lark/backend/ent/candidatecache"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CandidateCache is the model entity for the CandidateCache schema.
type CandidateCache struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID int `json:"target_id,omitempty"`
	// QueryKind holds the value of the "query_kind" field.
	QueryKind string `json:"query_kind,omitempty"`
	// SnapshotHash holds the value of the "snapshot_hash" field.
	SnapshotHash string `json:"snapshot_hash,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CandidateCache) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case candidatecache.FieldID, candidatecache.FieldUserID, candidatecache.FieldTargetID:
			values[i] = new(sql.NullInt64)
		case candidatecache.FieldTargetType, candidatecache.FieldQueryKind, candidatecache.FieldSnapshotHash, candidatecache.FieldPayload:
			values[i] = new(sql.NullString)
		case candidatecache.FieldExpiresAt, candidatecache.FieldCreatedAt, candidatecache.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CandidateCache fields.
func (_m *CandidateCache) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case candidatecache.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case candidatecache.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case candidatecache.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case candidatecache.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = int(value.Int64)
			}
		case candidatecache.FieldQueryKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query_kind", values[i])
			} else if value.Valid {
				_m.QueryKind = value.String
			}
		case candidatecache.FieldSnapshotHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_hash", values[i])
			} else if value.Valid {
				_m.SnapshotHash = value.String
			}
		case candidatecache.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case candidatecache.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case candidatecache.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case candidatecache.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CandidateCache.
// This includes values selected through modifiers, order, etc.
func (_m *CandidateCache) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CandidateCache.
// Note that you need to call CandidateCache.Unwrap() before calling this method if this CandidateCache
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CandidateCache) Update() *CandidateCacheUpdateOne {
	return NewCandidateCacheClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CandidateCache entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CandidateCache) Unwrap() *CandidateCache {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CandidateCache is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CandidateCache) String() string {
	var builder strings.Builder
	builder.WriteString("CandidateCache(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("query_kind=")
	builder.WriteString(_m.QueryKind)
	builder.WriteString(", ")
	builder.WriteString("snapshot_hash=")
	builder.WriteString(_m.SnapshotHash)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CandidateCaches is a parsable slice of CandidateCache.
type CandidateCaches []*CandidateCache
