// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lark/backend/ent/librarydirectory"
	"lark/backend/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LibraryDirectory is the model entity for the LibraryDirectory schema.
type LibraryDirectory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// WatchEnabled holds the value of the "watch_enabled" field.
	WatchEnabled bool `json:"watch_enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LibraryDirectoryQuery when eager-loading is set.
	Edges                    LibraryDirectoryEdges `json:"edges"`
	user_library_directories *int
	selectValues             sql.SelectValues
}

// LibraryDirectoryEdges holds the relations/edges for other nodes in the graph.
type LibraryDirectoryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LibraryDirectoryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LibraryDirectory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case librarydirectory.FieldWatchEnabled:
			values[i] = new(sql.NullBool)
		case librarydirectory.FieldID:
			values[i] = new(sql.NullInt64)
		case librarydirectory.FieldPath, librarydirectory.FieldNote:
			values[i] = new(sql.NullString)
		case librarydirectory.FieldCreatedAt, librarydirectory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case librarydirectory.ForeignKeys[0]: // user_library_directories
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LibraryDirectory fields.
func (_m *LibraryDirectory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case librarydirectory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case librarydirectory.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case librarydirectory.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case librarydirectory.FieldWatchEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field watch_enabled", values[i])
			} else if value.Valid {
				_m.WatchEnabled = value.Bool
			}
		case librarydirectory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case librarydirectory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case librarydirectory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_library_directories", value)
			} else if value.Valid {
				_m.user_library_directories = new(int)
				*_m.user_library_directories = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LibraryDirectory.
// This includes values selected through modifiers, order, etc.
func (_m *LibraryDirectory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LibraryDirectory entity.
func (_m *LibraryDirectory) QueryUser() *UserQuery {
	return NewLibraryDirectoryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this LibraryDirectory.
// Note that you need to call LibraryDirectory.Unwrap() before calling this method if this LibraryDirectory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LibraryDirectory) Update() *LibraryDirectoryUpdateOne {
	return NewLibraryDirectoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LibraryDirectory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LibraryDirectory) Unwrap() *LibraryDirectory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LibraryDirectory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LibraryDirectory) String() string {
	var builder strings.Builder
	builder.WriteString("LibraryDirectory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("watch_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.WatchEnabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LibraryDirectories is a parsable slice of LibraryDirectory.
type LibraryDirectories []*LibraryDirectory
