// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/playhistory"
	"lark/backend/ent/song"
	"lark/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayHistoryCreate is the builder for creating a PlayHistory entity.
type PlayHistoryCreate struct {
	config
	mutation *PlayHistoryMutation
	hooks    []Hook
}

// SetPlayedAt sets the "played_at" field.
func (_c *PlayHistoryCreate) SetPlayedAt(v time.Time) *PlayHistoryCreate {
	_c.mutation.SetPlayedAt(v)
	return _c
}

// SetNillablePlayedAt sets the "played_at" field if the given value is not nil.
func (_c *PlayHistoryCreate) SetNillablePlayedAt(v *time.Time) *PlayHistoryCreate {
	if v != nil {
		_c.SetPlayedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PlayHistoryCreate) SetUserID(id int) *PlayHistoryCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PlayHistoryCreate) SetUser(v *User) *PlayHistoryCreate {
	return _c.SetUserID(v.ID)
}

// SetSongID sets the "song" edge to the Song entity by ID.
func (_c *PlayHistoryCreate) SetSongID(id int) *PlayHistoryCreate {
	_c.mutation.SetSongID(id)
	return _c
}

// SetSong sets the "song" edge to the Song entity.
func (_c *PlayHistoryCreate) SetSong(v *Song) *PlayHistoryCreate {
	return _c.SetSongID(v.ID)
}

// Mutation returns the PlayHistoryMutation object of the builder.
func (_c *PlayHistoryCreate) Mutation() *PlayHistoryMutation {
	return _c.mutation
}

// Save creates the PlayHistory in the database.
func (_c *PlayHistoryCreate) Save(ctx context.Context) (*PlayHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayHistoryCreate) SaveX(ctx context.Context) *PlayHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayHistoryCreate) defaults() {
	if _, ok := _c.mutation.PlayedAt(); !ok {
		v := playhistory.DefaultPlayedAt()
		_c.mutation.SetPlayedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayHistoryCreate) check() error {
	if _, ok := _c.mutation.PlayedAt(); !ok {
		return &ValidationError{Name: "played_at", err: errors.New(`ent: missing required field "PlayHistory.played_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PlayHistory.user"`)}
	}
	if len(_c.mutation.SongIDs()) == 0 {
		return &ValidationError{Name: "song", err: errors.New(`ent: missing required edge "PlayHistory.song"`)}
	}
	return nil
}

func (_c *PlayHistoryCreate) sqlSave(ctx context.Context) (*PlayHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayHistoryCreate) createSpec() (*PlayHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playhistory.Table, sqlgraph.NewFieldSpec(playhistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PlayedAt(); ok {
		_spec.SetField(playhistory.FieldPlayedAt, field.TypeTime, value)
		_node.PlayedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playhistory.UserTable,
			Columns: []string{playhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_play_history = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SongIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playhistory.SongTable,
			Columns: []string{playhistory.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.song_play_history = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlayHistoryCreateBulk is the builder for creating many PlayHistory entities in bulk.
type PlayHistoryCreateBulk struct {
	config
	err      error
	builders []*PlayHistoryCreate
}

// Save creates the PlayHistory entities in the database.
func (_c *PlayHistoryCreateBulk) Save(ctx context.Context) ([]*PlayHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlayHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayHistoryCreateBulk) SaveX(ctx context.Context) []*PlayHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
