// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/playlist"
	"lark/backend/ent/song"
	"lark/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlaylistCreate is the builder for creating a Playlist entity.
type PlaylistCreate struct {
	config
	mutation *PlaylistMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PlaylistCreate) SetName(v string) *PlaylistCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlaylistCreate) SetDescription(v string) *PlaylistCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlaylistCreate) SetNillableDescription(v *string) *PlaylistCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCoverTheme sets the "cover_theme" field.
func (_c *PlaylistCreate) SetCoverTheme(v string) *PlaylistCreate {
	_c.mutation.SetCoverTheme(v)
	return _c
}

// SetNillableCoverTheme sets the "cover_theme" field if the given value is not nil.
func (_c *PlaylistCreate) SetNillableCoverTheme(v *string) *PlaylistCreate {
	if v != nil {
		_c.SetCoverTheme(*v)
	}
	return _c
}

// SetFavorite sets the "favorite" field.
func (_c *PlaylistCreate) SetFavorite(v bool) *PlaylistCreate {
	_c.mutation.SetFavorite(v)
	return _c
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_c *PlaylistCreate) SetNillableFavorite(v *bool) *PlaylistCreate {
	if v != nil {
		_c.SetFavorite(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlaylistCreate) SetCreatedAt(v time.Time) *PlaylistCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlaylistCreate) SetNillableCreatedAt(v *time.Time) *PlaylistCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlaylistCreate) SetUpdatedAt(v time.Time) *PlaylistCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlaylistCreate) SetNillableUpdatedAt(v *time.Time) *PlaylistCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddSongIDs adds the "songs" edge to the Song entity by IDs.
func (_c *PlaylistCreate) AddSongIDs(ids ...int) *PlaylistCreate {
	_c.mutation.AddSongIDs(ids...)
	return _c
}

// AddSongs adds the "songs" edges to the Song entity.
func (_c *PlaylistCreate) AddSongs(v ...*Song) *PlaylistCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSongIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *PlaylistCreate) SetOwnerID(id int) *PlaylistCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *PlaylistCreate) SetNillableOwnerID(id *int) *PlaylistCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *PlaylistCreate) SetOwner(v *User) *PlaylistCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the PlaylistMutation object of the builder.
func (_c *PlaylistCreate) Mutation() *PlaylistMutation {
	return _c.mutation
}

// Save creates the Playlist in the database.
func (_c *PlaylistCreate) Save(ctx context.Context) (*Playlist, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaylistCreate) SaveX(ctx context.Context) *Playlist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaylistCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := playlist.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CoverTheme(); !ok {
		v := playlist.DefaultCoverTheme
		_c.mutation.SetCoverTheme(v)
	}
	if _, ok := _c.mutation.Favorite(); !ok {
		v := playlist.DefaultFavorite
		_c.mutation.SetFavorite(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := playlist.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := playlist.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaylistCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Playlist.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := playlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Playlist.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Playlist.description"`)}
	}
	if _, ok := _c.mutation.CoverTheme(); !ok {
		return &ValidationError{Name: "cover_theme", err: errors.New(`ent: missing required field "Playlist.cover_theme"`)}
	}
	if _, ok := _c.mutation.Favorite(); !ok {
		return &ValidationError{Name: "favorite", err: errors.New(`ent: missing required field "Playlist.favorite"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Playlist.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Playlist.updated_at"`)}
	}
	return nil
}

func (_c *PlaylistCreate) sqlSave(ctx context.Context) (*Playlist, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaylistCreate) createSpec() (*Playlist, *sqlgraph.CreateSpec) {
	var (
		_node = &Playlist{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playlist.Table, sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(playlist.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(playlist.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CoverTheme(); ok {
		_spec.SetField(playlist.FieldCoverTheme, field.TypeString, value)
		_node.CoverTheme = value
	}
	if value, ok := _c.mutation.Favorite(); ok {
		_spec.SetField(playlist.FieldFavorite, field.TypeBool, value)
		_node.Favorite = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(playlist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(playlist.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   playlist.SongsTable,
			Columns: playlist.SongsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlist.OwnerTable,
			Columns: []string{playlist.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_playlists = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlaylistCreateBulk is the builder for creating many Playlist entities in bulk.
type PlaylistCreateBulk struct {
	config
	err      error
	builders []*PlaylistCreate
}

// Save creates the Playlist entities in the database.
func (_c *PlaylistCreateBulk) Save(ctx context.Context) ([]*Playlist, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Playlist, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaylistMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaylistCreateBulk) SaveX(ctx context.Context) []*Playlist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
