// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/plugin"
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PluginUpdate is the builder for updating Plugin entities.
type PluginUpdate struct {
	config
	hooks    []Hook
	mutation *PluginMutation
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdate) Where(ps ...predicate.Plugin) *PluginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PluginUpdate) SetName(v string) *PluginUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableName(v *string) *PluginUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginUpdate) SetVersion(v string) *PluginUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableVersion(v *string) *PluginUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PluginUpdate) SetDescription(v string) *PluginUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableDescription(v *string) *PluginUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PluginUpdate) SetAuthor(v string) *PluginUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableAuthor(v *string) *PluginUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetHomepage sets the "homepage" field.
func (_u *PluginUpdate) SetHomepage(v string) *PluginUpdate {
	_u.mutation.SetHomepage(v)
	return _u
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableHomepage(v *string) *PluginUpdate {
	if v != nil {
		_u.SetHomepage(*v)
	}
	return _u
}

// SetLicense sets the "license" field.
func (_u *PluginUpdate) SetLicense(v string) *PluginUpdate {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableLicense(v *string) *PluginUpdate {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// SetEntryPath sets the "entry_path" field.
func (_u *PluginUpdate) SetEntryPath(v string) *PluginUpdate {
	_u.mutation.SetEntryPath(v)
	return _u
}

// SetNillableEntryPath sets the "entry_path" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableEntryPath(v *string) *PluginUpdate {
	if v != nil {
		_u.SetEntryPath(*v)
	}
	return _u
}

// SetMain sets the "main" field.
func (_u *PluginUpdate) SetMain(v string) *PluginUpdate {
	_u.mutation.SetMain(v)
	return _u
}

// SetNillableMain sets the "main" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableMain(v *string) *PluginUpdate {
	if v != nil {
		_u.SetMain(*v)
	}
	return _u
}

// SetMinHostVersion sets the "min_host_version" field.
func (_u *PluginUpdate) SetMinHostVersion(v string) *PluginUpdate {
	_u.mutation.SetMinHostVersion(v)
	return _u
}

// SetNillableMinHostVersion sets the "min_host_version" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableMinHostVersion(v *string) *PluginUpdate {
	if v != nil {
		_u.SetMinHostVersion(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *PluginUpdate) SetPermissions(v []string) *PluginUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *PluginUpdate) AppendPermissions(v []string) *PluginUpdate {
	_u.mutation.AppendPermissions(v)
	return _u
}

// SetPublicPaths sets the "public_paths" field.
func (_u *PluginUpdate) SetPublicPaths(v []string) *PluginUpdate {
	_u.mutation.SetPublicPaths(v)
	return _u
}

// AppendPublicPaths appends value to the "public_paths" field.
func (_u *PluginUpdate) AppendPublicPaths(v []string) *PluginUpdate {
	_u.mutation.AppendPublicPaths(v)
	return _u
}

// SetExternalPaths sets the "external_paths" field.
func (_u *PluginUpdate) SetExternalPaths(v []string) *PluginUpdate {
	_u.mutation.SetExternalPaths(v)
	return _u
}

// AppendExternalPaths appends value to the "external_paths" field.
func (_u *PluginUpdate) AppendExternalPaths(v []string) *PluginUpdate {
	_u.mutation.AppendExternalPaths(v)
	return _u
}

// SetIcon sets the "icon" field.
func (_u *PluginUpdate) SetIcon(v string) *PluginUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableIcon(v *string) *PluginUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetUpdateURL sets the "update_url" field.
func (_u *PluginUpdate) SetUpdateURL(v string) *PluginUpdate {
	_u.mutation.SetUpdateURL(v)
	return _u
}

// SetNillableUpdateURL sets the "update_url" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableUpdateURL(v *string) *PluginUpdate {
	if v != nil {
		_u.SetUpdateURL(*v)
	}
	return _u
}

// SetDownloadURL sets the "download_url" field.
func (_u *PluginUpdate) SetDownloadURL(v string) *PluginUpdate {
	_u.mutation.SetDownloadURL(v)
	return _u
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableDownloadURL(v *string) *PluginUpdate {
	if v != nil {
		_u.SetDownloadURL(*v)
	}
	return _u
}

// SetRenderEngine sets the "render_engine" field.
func (_u *PluginUpdate) SetRenderEngine(v string) *PluginUpdate {
	_u.mutation.SetRenderEngine(v)
	return _u
}

// SetNillableRenderEngine sets the "render_engine" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableRenderEngine(v *string) *PluginUpdate {
	if v != nil {
		_u.SetRenderEngine(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginUpdate) SetStatus(v string) *PluginUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableStatus(v *string) *PluginUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetZipHash sets the "zip_hash" field.
func (_u *PluginUpdate) SetZipHash(v string) *PluginUpdate {
	_u.mutation.SetZipHash(v)
	return _u
}

// SetNillableZipHash sets the "zip_hash" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableZipHash(v *string) *PluginUpdate {
	if v != nil {
		_u.SetZipHash(*v)
	}
	return _u
}

// SetEntryHash sets the "entry_hash" field.
func (_u *PluginUpdate) SetEntryHash(v string) *PluginUpdate {
	_u.mutation.SetEntryHash(v)
	return _u
}

// SetNillableEntryHash sets the "entry_hash" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableEntryHash(v *string) *PluginUpdate {
	if v != nil {
		_u.SetEntryHash(*v)
	}
	return _u
}

// SetFileModTime sets the "file_mod_time" field.
func (_u *PluginUpdate) SetFileModTime(v string) *PluginUpdate {
	_u.mutation.SetFileModTime(v)
	return _u
}

// SetNillableFileModTime sets the "file_mod_time" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableFileModTime(v *string) *PluginUpdate {
	if v != nil {
		_u.SetFileModTime(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *PluginUpdate) SetFilePath(v string) *PluginUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableFilePath(v *string) *PluginUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PluginUpdate) SetCreatedAt(v time.Time) *PluginUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableCreatedAt(v *time.Time) *PluginUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginUpdate) SetUpdatedAt(v time.Time) *PluginUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdate) Mutation() *PluginMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryPath(); ok {
		if err := plugin.EntryPathValidator(v); err != nil {
			return &ValidationError{Name: "entry_path", err: fmt.Errorf(`ent: validator failed for field "Plugin.entry_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Main(); ok {
		if err := plugin.MainValidator(v); err != nil {
			return &ValidationError{Name: "main", err: fmt.Errorf(`ent: validator failed for field "Plugin.main": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Homepage(); ok {
		_spec.SetField(plugin.FieldHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryPath(); ok {
		_spec.SetField(plugin.FieldEntryPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Main(); ok {
		_spec.SetField(plugin.FieldMain, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinHostVersion(); ok {
		_spec.SetField(plugin.FieldMinHostVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(plugin.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldPermissions, value)
		})
	}
	if value, ok := _u.mutation.PublicPaths(); ok {
		_spec.SetField(plugin.FieldPublicPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldPublicPaths, value)
		})
	}
	if value, ok := _u.mutation.ExternalPaths(); ok {
		_spec.SetField(plugin.FieldExternalPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExternalPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldExternalPaths, value)
		})
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(plugin.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdateURL(); ok {
		_spec.SetField(plugin.FieldUpdateURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadURL(); ok {
		_spec.SetField(plugin.FieldDownloadURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderEngine(); ok {
		_spec.SetField(plugin.FieldRenderEngine, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZipHash(); ok {
		_spec.SetField(plugin.FieldZipHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryHash(); ok {
		_spec.SetField(plugin.FieldEntryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileModTime(); ok {
		_spec.SetField(plugin.FieldFileModTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(plugin.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginUpdateOne is the builder for updating a single Plugin entity.
type PluginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginMutation
}

// SetName sets the "name" field.
func (_u *PluginUpdateOne) SetName(v string) *PluginUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableName(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginUpdateOne) SetVersion(v string) *PluginUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableVersion(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PluginUpdateOne) SetDescription(v string) *PluginUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableDescription(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PluginUpdateOne) SetAuthor(v string) *PluginUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableAuthor(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetHomepage sets the "homepage" field.
func (_u *PluginUpdateOne) SetHomepage(v string) *PluginUpdateOne {
	_u.mutation.SetHomepage(v)
	return _u
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableHomepage(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetHomepage(*v)
	}
	return _u
}

// SetLicense sets the "license" field.
func (_u *PluginUpdateOne) SetLicense(v string) *PluginUpdateOne {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableLicense(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// SetEntryPath sets the "entry_path" field.
func (_u *PluginUpdateOne) SetEntryPath(v string) *PluginUpdateOne {
	_u.mutation.SetEntryPath(v)
	return _u
}

// SetNillableEntryPath sets the "entry_path" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableEntryPath(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetEntryPath(*v)
	}
	return _u
}

// SetMain sets the "main" field.
func (_u *PluginUpdateOne) SetMain(v string) *PluginUpdateOne {
	_u.mutation.SetMain(v)
	return _u
}

// SetNillableMain sets the "main" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableMain(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetMain(*v)
	}
	return _u
}

// SetMinHostVersion sets the "min_host_version" field.
func (_u *PluginUpdateOne) SetMinHostVersion(v string) *PluginUpdateOne {
	_u.mutation.SetMinHostVersion(v)
	return _u
}

// SetNillableMinHostVersion sets the "min_host_version" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableMinHostVersion(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetMinHostVersion(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *PluginUpdateOne) SetPermissions(v []string) *PluginUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *PluginUpdateOne) AppendPermissions(v []string) *PluginUpdateOne {
	_u.mutation.AppendPermissions(v)
	return _u
}

// SetPublicPaths sets the "public_paths" field.
func (_u *PluginUpdateOne) SetPublicPaths(v []string) *PluginUpdateOne {
	_u.mutation.SetPublicPaths(v)
	return _u
}

// AppendPublicPaths appends value to the "public_paths" field.
func (_u *PluginUpdateOne) AppendPublicPaths(v []string) *PluginUpdateOne {
	_u.mutation.AppendPublicPaths(v)
	return _u
}

// SetExternalPaths sets the "external_paths" field.
func (_u *PluginUpdateOne) SetExternalPaths(v []string) *PluginUpdateOne {
	_u.mutation.SetExternalPaths(v)
	return _u
}

// AppendExternalPaths appends value to the "external_paths" field.
func (_u *PluginUpdateOne) AppendExternalPaths(v []string) *PluginUpdateOne {
	_u.mutation.AppendExternalPaths(v)
	return _u
}

// SetIcon sets the "icon" field.
func (_u *PluginUpdateOne) SetIcon(v string) *PluginUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableIcon(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetUpdateURL sets the "update_url" field.
func (_u *PluginUpdateOne) SetUpdateURL(v string) *PluginUpdateOne {
	_u.mutation.SetUpdateURL(v)
	return _u
}

// SetNillableUpdateURL sets the "update_url" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableUpdateURL(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetUpdateURL(*v)
	}
	return _u
}

// SetDownloadURL sets the "download_url" field.
func (_u *PluginUpdateOne) SetDownloadURL(v string) *PluginUpdateOne {
	_u.mutation.SetDownloadURL(v)
	return _u
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableDownloadURL(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetDownloadURL(*v)
	}
	return _u
}

// SetRenderEngine sets the "render_engine" field.
func (_u *PluginUpdateOne) SetRenderEngine(v string) *PluginUpdateOne {
	_u.mutation.SetRenderEngine(v)
	return _u
}

// SetNillableRenderEngine sets the "render_engine" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableRenderEngine(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetRenderEngine(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginUpdateOne) SetStatus(v string) *PluginUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableStatus(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetZipHash sets the "zip_hash" field.
func (_u *PluginUpdateOne) SetZipHash(v string) *PluginUpdateOne {
	_u.mutation.SetZipHash(v)
	return _u
}

// SetNillableZipHash sets the "zip_hash" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableZipHash(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetZipHash(*v)
	}
	return _u
}

// SetEntryHash sets the "entry_hash" field.
func (_u *PluginUpdateOne) SetEntryHash(v string) *PluginUpdateOne {
	_u.mutation.SetEntryHash(v)
	return _u
}

// SetNillableEntryHash sets the "entry_hash" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableEntryHash(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetEntryHash(*v)
	}
	return _u
}

// SetFileModTime sets the "file_mod_time" field.
func (_u *PluginUpdateOne) SetFileModTime(v string) *PluginUpdateOne {
	_u.mutation.SetFileModTime(v)
	return _u
}

// SetNillableFileModTime sets the "file_mod_time" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableFileModTime(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetFileModTime(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *PluginUpdateOne) SetFilePath(v string) *PluginUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableFilePath(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PluginUpdateOne) SetCreatedAt(v time.Time) *PluginUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableCreatedAt(v *time.Time) *PluginUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginUpdateOne) SetUpdatedAt(v time.Time) *PluginUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdateOne) Mutation() *PluginMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdateOne) Where(ps ...predicate.Plugin) *PluginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginUpdateOne) Select(field string, fields ...string) *PluginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plugin entity.
func (_u *PluginUpdateOne) Save(ctx context.Context) (*Plugin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdateOne) SaveX(ctx context.Context) *Plugin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryPath(); ok {
		if err := plugin.EntryPathValidator(v); err != nil {
			return &ValidationError{Name: "entry_path", err: fmt.Errorf(`ent: validator failed for field "Plugin.entry_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Main(); ok {
		if err := plugin.MainValidator(v); err != nil {
			return &ValidationError{Name: "main", err: fmt.Errorf(`ent: validator failed for field "Plugin.main": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdateOne) sqlSave(ctx context.Context) (_node *Plugin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plugin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugin.FieldID)
		for _, f := range fields {
			if !plugin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plugin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Homepage(); ok {
		_spec.SetField(plugin.FieldHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryPath(); ok {
		_spec.SetField(plugin.FieldEntryPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Main(); ok {
		_spec.SetField(plugin.FieldMain, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinHostVersion(); ok {
		_spec.SetField(plugin.FieldMinHostVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(plugin.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldPermissions, value)
		})
	}
	if value, ok := _u.mutation.PublicPaths(); ok {
		_spec.SetField(plugin.FieldPublicPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldPublicPaths, value)
		})
	}
	if value, ok := _u.mutation.ExternalPaths(); ok {
		_spec.SetField(plugin.FieldExternalPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExternalPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldExternalPaths, value)
		})
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(plugin.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdateURL(); ok {
		_spec.SetField(plugin.FieldUpdateURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DownloadURL(); ok {
		_spec.SetField(plugin.FieldDownloadURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderEngine(); ok {
		_spec.SetField(plugin.FieldRenderEngine, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZipHash(); ok {
		_spec.SetField(plugin.FieldZipHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryHash(); ok {
		_spec.SetField(plugin.FieldEntryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileModTime(); ok {
		_spec.SetField(plugin.FieldFileModTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(plugin.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Plugin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
