// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lark/backend/ent/pluginstorage"
	"lark/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PluginStorageDelete is the builder for deleting a PluginStorage entity.
type PluginStorageDelete struct {
	config
	hooks    []Hook
	mutation *PluginStorageMutation
}

// Where appends a list predicates to the PluginStorageDelete builder.
func (_d *PluginStorageDelete) Where(ps ...predicate.PluginStorage) *PluginStorageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PluginStorageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PluginStorageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PluginStorageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pluginstorage.Table, sqlgraph.NewFieldSpec(pluginstorage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PluginStorageDeleteOne is the builder for deleting a single PluginStorage entity.
type PluginStorageDeleteOne struct {
	_d *PluginStorageDelete
}

// Where appends a list predicates to the PluginStorageDelete builder.
func (_d *PluginStorageDeleteOne) Where(ps ...predicate.PluginStorage) *PluginStorageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PluginStorageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pluginstorage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PluginStorageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
