// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/plugin"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PluginCreate is the builder for creating a Plugin entity.
type PluginCreate struct {
	config
	mutation *PluginMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PluginCreate) SetName(v string) *PluginCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PluginCreate) SetVersion(v string) *PluginCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PluginCreate) SetDescription(v string) *PluginCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PluginCreate) SetNillableDescription(v *string) *PluginCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *PluginCreate) SetAuthor(v string) *PluginCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *PluginCreate) SetNillableAuthor(v *string) *PluginCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetHomepage sets the "homepage" field.
func (_c *PluginCreate) SetHomepage(v string) *PluginCreate {
	_c.mutation.SetHomepage(v)
	return _c
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (_c *PluginCreate) SetNillableHomepage(v *string) *PluginCreate {
	if v != nil {
		_c.SetHomepage(*v)
	}
	return _c
}

// SetLicense sets the "license" field.
func (_c *PluginCreate) SetLicense(v string) *PluginCreate {
	_c.mutation.SetLicense(v)
	return _c
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_c *PluginCreate) SetNillableLicense(v *string) *PluginCreate {
	if v != nil {
		_c.SetLicense(*v)
	}
	return _c
}

// SetEntryPath sets the "entry_path" field.
func (_c *PluginCreate) SetEntryPath(v string) *PluginCreate {
	_c.mutation.SetEntryPath(v)
	return _c
}

// SetMain sets the "main" field.
func (_c *PluginCreate) SetMain(v string) *PluginCreate {
	_c.mutation.SetMain(v)
	return _c
}

// SetMinHostVersion sets the "min_host_version" field.
func (_c *PluginCreate) SetMinHostVersion(v string) *PluginCreate {
	_c.mutation.SetMinHostVersion(v)
	return _c
}

// SetNillableMinHostVersion sets the "min_host_version" field if the given value is not nil.
func (_c *PluginCreate) SetNillableMinHostVersion(v *string) *PluginCreate {
	if v != nil {
		_c.SetMinHostVersion(*v)
	}
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *PluginCreate) SetPermissions(v []string) *PluginCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetPublicPaths sets the "public_paths" field.
func (_c *PluginCreate) SetPublicPaths(v []string) *PluginCreate {
	_c.mutation.SetPublicPaths(v)
	return _c
}

// SetExternalPaths sets the "external_paths" field.
func (_c *PluginCreate) SetExternalPaths(v []string) *PluginCreate {
	_c.mutation.SetExternalPaths(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *PluginCreate) SetIcon(v string) *PluginCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *PluginCreate) SetNillableIcon(v *string) *PluginCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetUpdateURL sets the "update_url" field.
func (_c *PluginCreate) SetUpdateURL(v string) *PluginCreate {
	_c.mutation.SetUpdateURL(v)
	return _c
}

// SetNillableUpdateURL sets the "update_url" field if the given value is not nil.
func (_c *PluginCreate) SetNillableUpdateURL(v *string) *PluginCreate {
	if v != nil {
		_c.SetUpdateURL(*v)
	}
	return _c
}

// SetDownloadURL sets the "download_url" field.
func (_c *PluginCreate) SetDownloadURL(v string) *PluginCreate {
	_c.mutation.SetDownloadURL(v)
	return _c
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_c *PluginCreate) SetNillableDownloadURL(v *string) *PluginCreate {
	if v != nil {
		_c.SetDownloadURL(*v)
	}
	return _c
}

// SetRenderEngine sets the "render_engine" field.
func (_c *PluginCreate) SetRenderEngine(v string) *PluginCreate {
	_c.mutation.SetRenderEngine(v)
	return _c
}

// SetNillableRenderEngine sets the "render_engine" field if the given value is not nil.
func (_c *PluginCreate) SetNillableRenderEngine(v *string) *PluginCreate {
	if v != nil {
		_c.SetRenderEngine(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PluginCreate) SetStatus(v string) *PluginCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PluginCreate) SetNillableStatus(v *string) *PluginCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetZipHash sets the "zip_hash" field.
func (_c *PluginCreate) SetZipHash(v string) *PluginCreate {
	_c.mutation.SetZipHash(v)
	return _c
}

// SetNillableZipHash sets the "zip_hash" field if the given value is not nil.
func (_c *PluginCreate) SetNillableZipHash(v *string) *PluginCreate {
	if v != nil {
		_c.SetZipHash(*v)
	}
	return _c
}

// SetEntryHash sets the "entry_hash" field.
func (_c *PluginCreate) SetEntryHash(v string) *PluginCreate {
	_c.mutation.SetEntryHash(v)
	return _c
}

// SetNillableEntryHash sets the "entry_hash" field if the given value is not nil.
func (_c *PluginCreate) SetNillableEntryHash(v *string) *PluginCreate {
	if v != nil {
		_c.SetEntryHash(*v)
	}
	return _c
}

// SetFileModTime sets the "file_mod_time" field.
func (_c *PluginCreate) SetFileModTime(v string) *PluginCreate {
	_c.mutation.SetFileModTime(v)
	return _c
}

// SetNillableFileModTime sets the "file_mod_time" field if the given value is not nil.
func (_c *PluginCreate) SetNillableFileModTime(v *string) *PluginCreate {
	if v != nil {
		_c.SetFileModTime(*v)
	}
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *PluginCreate) SetFilePath(v string) *PluginCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_c *PluginCreate) SetNillableFilePath(v *string) *PluginCreate {
	if v != nil {
		_c.SetFilePath(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginCreate) SetCreatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableCreatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginCreate) SetUpdatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableUpdatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PluginMutation object of the builder.
func (_c *PluginCreate) Mutation() *PluginMutation {
	return _c.mutation
}

// Save creates the Plugin in the database.
func (_c *PluginCreate) Save(ctx context.Context) (*Plugin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginCreate) SaveX(ctx context.Context) *Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := plugin.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Author(); !ok {
		v := plugin.DefaultAuthor
		_c.mutation.SetAuthor(v)
	}
	if _, ok := _c.mutation.Homepage(); !ok {
		v := plugin.DefaultHomepage
		_c.mutation.SetHomepage(v)
	}
	if _, ok := _c.mutation.License(); !ok {
		v := plugin.DefaultLicense
		_c.mutation.SetLicense(v)
	}
	if _, ok := _c.mutation.MinHostVersion(); !ok {
		v := plugin.DefaultMinHostVersion
		_c.mutation.SetMinHostVersion(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := plugin.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.UpdateURL(); !ok {
		v := plugin.DefaultUpdateURL
		_c.mutation.SetUpdateURL(v)
	}
	if _, ok := _c.mutation.DownloadURL(); !ok {
		v := plugin.DefaultDownloadURL
		_c.mutation.SetDownloadURL(v)
	}
	if _, ok := _c.mutation.RenderEngine(); !ok {
		v := plugin.DefaultRenderEngine
		_c.mutation.SetRenderEngine(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := plugin.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ZipHash(); !ok {
		v := plugin.DefaultZipHash
		_c.mutation.SetZipHash(v)
	}
	if _, ok := _c.mutation.EntryHash(); !ok {
		v := plugin.DefaultEntryHash
		_c.mutation.SetEntryHash(v)
	}
	if _, ok := _c.mutation.FileModTime(); !ok {
		v := plugin.DefaultFileModTime
		_c.mutation.SetFileModTime(v)
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		v := plugin.DefaultFilePath
		_c.mutation.SetFilePath(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plugin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plugin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plugin.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Plugin.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Plugin.description"`)}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Plugin.author"`)}
	}
	if _, ok := _c.mutation.Homepage(); !ok {
		return &ValidationError{Name: "homepage", err: errors.New(`ent: missing required field "Plugin.homepage"`)}
	}
	if _, ok := _c.mutation.License(); !ok {
		return &ValidationError{Name: "license", err: errors.New(`ent: missing required field "Plugin.license"`)}
	}
	if _, ok := _c.mutation.EntryPath(); !ok {
		return &ValidationError{Name: "entry_path", err: errors.New(`ent: missing required field "Plugin.entry_path"`)}
	}
	if v, ok := _c.mutation.EntryPath(); ok {
		if err := plugin.EntryPathValidator(v); err != nil {
			return &ValidationError{Name: "entry_path", err: fmt.Errorf(`ent: validator failed for field "Plugin.entry_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Main(); !ok {
		return &ValidationError{Name: "main", err: errors.New(`ent: missing required field "Plugin.main"`)}
	}
	if v, ok := _c.mutation.Main(); ok {
		if err := plugin.MainValidator(v); err != nil {
			return &ValidationError{Name: "main", err: fmt.Errorf(`ent: validator failed for field "Plugin.main": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinHostVersion(); !ok {
		return &ValidationError{Name: "min_host_version", err: errors.New(`ent: missing required field "Plugin.min_host_version"`)}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "Plugin.permissions"`)}
	}
	if _, ok := _c.mutation.PublicPaths(); !ok {
		return &ValidationError{Name: "public_paths", err: errors.New(`ent: missing required field "Plugin.public_paths"`)}
	}
	if _, ok := _c.mutation.ExternalPaths(); !ok {
		return &ValidationError{Name: "external_paths", err: errors.New(`ent: missing required field "Plugin.external_paths"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Plugin.icon"`)}
	}
	if _, ok := _c.mutation.UpdateURL(); !ok {
		return &ValidationError{Name: "update_url", err: errors.New(`ent: missing required field "Plugin.update_url"`)}
	}
	if _, ok := _c.mutation.DownloadURL(); !ok {
		return &ValidationError{Name: "download_url", err: errors.New(`ent: missing required field "Plugin.download_url"`)}
	}
	if _, ok := _c.mutation.RenderEngine(); !ok {
		return &ValidationError{Name: "render_engine", err: errors.New(`ent: missing required field "Plugin.render_engine"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Plugin.status"`)}
	}
	if _, ok := _c.mutation.ZipHash(); !ok {
		return &ValidationError{Name: "zip_hash", err: errors.New(`ent: missing required field "Plugin.zip_hash"`)}
	}
	if _, ok := _c.mutation.EntryHash(); !ok {
		return &ValidationError{Name: "entry_hash", err: errors.New(`ent: missing required field "Plugin.entry_hash"`)}
	}
	if _, ok := _c.mutation.FileModTime(); !ok {
		return &ValidationError{Name: "file_mod_time", err: errors.New(`ent: missing required field "Plugin.file_mod_time"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Plugin.file_path"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plugin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plugin.updated_at"`)}
	}
	return nil
}

func (_c *PluginCreate) sqlSave(ctx context.Context) (*Plugin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginCreate) createSpec() (*Plugin, *sqlgraph.CreateSpec) {
	var (
		_node = &Plugin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plugin.Table, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.Homepage(); ok {
		_spec.SetField(plugin.FieldHomepage, field.TypeString, value)
		_node.Homepage = value
	}
	if value, ok := _c.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
		_node.License = value
	}
	if value, ok := _c.mutation.EntryPath(); ok {
		_spec.SetField(plugin.FieldEntryPath, field.TypeString, value)
		_node.EntryPath = value
	}
	if value, ok := _c.mutation.Main(); ok {
		_spec.SetField(plugin.FieldMain, field.TypeString, value)
		_node.Main = value
	}
	if value, ok := _c.mutation.MinHostVersion(); ok {
		_spec.SetField(plugin.FieldMinHostVersion, field.TypeString, value)
		_node.MinHostVersion = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(plugin.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.PublicPaths(); ok {
		_spec.SetField(plugin.FieldPublicPaths, field.TypeJSON, value)
		_node.PublicPaths = value
	}
	if value, ok := _c.mutation.ExternalPaths(); ok {
		_spec.SetField(plugin.FieldExternalPaths, field.TypeJSON, value)
		_node.ExternalPaths = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(plugin.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.UpdateURL(); ok {
		_spec.SetField(plugin.FieldUpdateURL, field.TypeString, value)
		_node.UpdateURL = value
	}
	if value, ok := _c.mutation.DownloadURL(); ok {
		_spec.SetField(plugin.FieldDownloadURL, field.TypeString, value)
		_node.DownloadURL = value
	}
	if value, ok := _c.mutation.RenderEngine(); ok {
		_spec.SetField(plugin.FieldRenderEngine, field.TypeString, value)
		_node.RenderEngine = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ZipHash(); ok {
		_spec.SetField(plugin.FieldZipHash, field.TypeString, value)
		_node.ZipHash = value
	}
	if value, ok := _c.mutation.EntryHash(); ok {
		_spec.SetField(plugin.FieldEntryHash, field.TypeString, value)
		_node.EntryHash = value
	}
	if value, ok := _c.mutation.FileModTime(); ok {
		_spec.SetField(plugin.FieldFileModTime, field.TypeString, value)
		_node.FileModTime = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(plugin.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PluginCreateBulk is the builder for creating many Plugin entities in bulk.
type PluginCreateBulk struct {
	config
	err      error
	builders []*PluginCreate
}

// Save creates the Plugin entities in the database.
func (_c *PluginCreateBulk) Save(ctx context.Context) ([]*Plugin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plugin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginCreateBulk) SaveX(ctx context.Context) []*Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
