// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/pluginstorage"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PluginStorageCreate is the builder for creating a PluginStorage entity.
type PluginStorageCreate struct {
	config
	mutation *PluginStorageMutation
	hooks    []Hook
}

// SetPluginEntryPath sets the "plugin_entry_path" field.
func (_c *PluginStorageCreate) SetPluginEntryPath(v string) *PluginStorageCreate {
	_c.mutation.SetPluginEntryPath(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *PluginStorageCreate) SetNamespace(v string) *PluginStorageCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *PluginStorageCreate) SetKey(v string) *PluginStorageCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *PluginStorageCreate) SetValue(v string) *PluginStorageCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *PluginStorageCreate) SetNillableValue(v *string) *PluginStorageCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginStorageCreate) SetCreatedAt(v time.Time) *PluginStorageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginStorageCreate) SetNillableCreatedAt(v *time.Time) *PluginStorageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginStorageCreate) SetUpdatedAt(v time.Time) *PluginStorageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginStorageCreate) SetNillableUpdatedAt(v *time.Time) *PluginStorageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PluginStorageMutation object of the builder.
func (_c *PluginStorageCreate) Mutation() *PluginStorageMutation {
	return _c.mutation
}

// Save creates the PluginStorage in the database.
func (_c *PluginStorageCreate) Save(ctx context.Context) (*PluginStorage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginStorageCreate) SaveX(ctx context.Context) *PluginStorage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginStorageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginStorageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginStorageCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := pluginstorage.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pluginstorage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pluginstorage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginStorageCreate) check() error {
	if _, ok := _c.mutation.PluginEntryPath(); !ok {
		return &ValidationError{Name: "plugin_entry_path", err: errors.New(`ent: missing required field "PluginStorage.plugin_entry_path"`)}
	}
	if v, ok := _c.mutation.PluginEntryPath(); ok {
		if err := pluginstorage.PluginEntryPathValidator(v); err != nil {
			return &ValidationError{Name: "plugin_entry_path", err: fmt.Errorf(`ent: validator failed for field "PluginStorage.plugin_entry_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "PluginStorage.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := pluginstorage.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "PluginStorage.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PluginStorage.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := pluginstorage.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PluginStorage.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "PluginStorage.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PluginStorage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginStorage.updated_at"`)}
	}
	return nil
}

func (_c *PluginStorageCreate) sqlSave(ctx context.Context) (*PluginStorage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginStorageCreate) createSpec() (*PluginStorage, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginStorage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginstorage.Table, sqlgraph.NewFieldSpec(pluginstorage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PluginEntryPath(); ok {
		_spec.SetField(pluginstorage.FieldPluginEntryPath, field.TypeString, value)
		_node.PluginEntryPath = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(pluginstorage.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(pluginstorage.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(pluginstorage.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pluginstorage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginstorage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PluginStorageCreateBulk is the builder for creating many PluginStorage entities in bulk.
type PluginStorageCreateBulk struct {
	config
	err      error
	builders []*PluginStorageCreate
}

// Save creates the PluginStorage entities in the database.
func (_c *PluginStorageCreateBulk) Save(ctx context.Context) ([]*PluginStorage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginStorage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginStorageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginStorageCreateBulk) SaveX(ctx context.Context) []*PluginStorage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginStorageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginStorageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
