// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lark/backend/ent/album"
	"lark/backend/ent/appsetting"
	"lark/backend/ent/artist"
	"lark/backend/ent/librarydirectory"
	"lark/backend/ent/playhistory"
	"lark/backend/ent/playlist"
	"lark/backend/ent/schema"
	"lark/backend/ent/session"
	"lark/backend/ent/song"
	"lark/backend/ent/user"
	"lark/backend/ent/useralbumfavorite"
	"lark/backend/ent/userartistfavorite"
	"lark/backend/ent/userradiofavorite"
	"lark/backend/ent/usersongfavorite"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescTitle is the schema descriptor for title field.
	albumDescTitle := albumFields[0].Descriptor()
	// album.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	album.TitleValidator = albumDescTitle.Validators[0].(func(string) error)
	// albumDescAlbumArtist is the schema descriptor for album_artist field.
	albumDescAlbumArtist := albumFields[1].Descriptor()
	// album.DefaultAlbumArtist holds the default value on creation for the album_artist field.
	album.DefaultAlbumArtist = albumDescAlbumArtist.Default.(string)
	// albumDescCoverPath is the schema descriptor for cover_path field.
	albumDescCoverPath := albumFields[2].Descriptor()
	// album.DefaultCoverPath holds the default value on creation for the cover_path field.
	album.DefaultCoverPath = albumDescCoverPath.Default.(string)
	// albumDescYear is the schema descriptor for year field.
	albumDescYear := albumFields[3].Descriptor()
	// album.DefaultYear holds the default value on creation for the year field.
	album.DefaultYear = albumDescYear.Default.(int)
	// albumDescFavorite is the schema descriptor for favorite field.
	albumDescFavorite := albumFields[4].Descriptor()
	// album.DefaultFavorite holds the default value on creation for the favorite field.
	album.DefaultFavorite = albumDescFavorite.Default.(bool)
	// albumDescCreatedAt is the schema descriptor for created_at field.
	albumDescCreatedAt := albumFields[5].Descriptor()
	// album.DefaultCreatedAt holds the default value on creation for the created_at field.
	album.DefaultCreatedAt = albumDescCreatedAt.Default.(func() time.Time)
	// albumDescUpdatedAt is the schema descriptor for updated_at field.
	albumDescUpdatedAt := albumFields[6].Descriptor()
	// album.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	album.DefaultUpdatedAt = albumDescUpdatedAt.Default.(func() time.Time)
	// album.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	album.UpdateDefaultUpdatedAt = albumDescUpdatedAt.UpdateDefault.(func() time.Time)
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescKey is the schema descriptor for key field.
	appsettingDescKey := appsettingFields[0].Descriptor()
	// appsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	appsetting.KeyValidator = appsettingDescKey.Validators[0].(func(string) error)
	// appsettingDescValue is the schema descriptor for value field.
	appsettingDescValue := appsettingFields[1].Descriptor()
	// appsetting.DefaultValue holds the default value on creation for the value field.
	appsetting.DefaultValue = appsettingDescValue.Default.(string)
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingFields[2].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingFields[3].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	artistFields := schema.Artist{}.Fields()
	_ = artistFields
	// artistDescName is the schema descriptor for name field.
	artistDescName := artistFields[0].Descriptor()
	// artist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artist.NameValidator = artistDescName.Validators[0].(func(string) error)
	// artistDescCreatedAt is the schema descriptor for created_at field.
	artistDescCreatedAt := artistFields[1].Descriptor()
	// artist.DefaultCreatedAt holds the default value on creation for the created_at field.
	artist.DefaultCreatedAt = artistDescCreatedAt.Default.(func() time.Time)
	// artistDescUpdatedAt is the schema descriptor for updated_at field.
	artistDescUpdatedAt := artistFields[2].Descriptor()
	// artist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	artist.DefaultUpdatedAt = artistDescUpdatedAt.Default.(func() time.Time)
	// artist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	artist.UpdateDefaultUpdatedAt = artistDescUpdatedAt.UpdateDefault.(func() time.Time)
	librarydirectoryFields := schema.LibraryDirectory{}.Fields()
	_ = librarydirectoryFields
	// librarydirectoryDescPath is the schema descriptor for path field.
	librarydirectoryDescPath := librarydirectoryFields[0].Descriptor()
	// librarydirectory.PathValidator is a validator for the "path" field. It is called by the builders before save.
	librarydirectory.PathValidator = librarydirectoryDescPath.Validators[0].(func(string) error)
	// librarydirectoryDescNote is the schema descriptor for note field.
	librarydirectoryDescNote := librarydirectoryFields[1].Descriptor()
	// librarydirectory.DefaultNote holds the default value on creation for the note field.
	librarydirectory.DefaultNote = librarydirectoryDescNote.Default.(string)
	// librarydirectoryDescWatchEnabled is the schema descriptor for watch_enabled field.
	librarydirectoryDescWatchEnabled := librarydirectoryFields[2].Descriptor()
	// librarydirectory.DefaultWatchEnabled holds the default value on creation for the watch_enabled field.
	librarydirectory.DefaultWatchEnabled = librarydirectoryDescWatchEnabled.Default.(bool)
	// librarydirectoryDescCreatedAt is the schema descriptor for created_at field.
	librarydirectoryDescCreatedAt := librarydirectoryFields[3].Descriptor()
	// librarydirectory.DefaultCreatedAt holds the default value on creation for the created_at field.
	librarydirectory.DefaultCreatedAt = librarydirectoryDescCreatedAt.Default.(func() time.Time)
	// librarydirectoryDescUpdatedAt is the schema descriptor for updated_at field.
	librarydirectoryDescUpdatedAt := librarydirectoryFields[4].Descriptor()
	// librarydirectory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	librarydirectory.DefaultUpdatedAt = librarydirectoryDescUpdatedAt.Default.(func() time.Time)
	// librarydirectory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	librarydirectory.UpdateDefaultUpdatedAt = librarydirectoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	playhistoryFields := schema.PlayHistory{}.Fields()
	_ = playhistoryFields
	// playhistoryDescPlayedAt is the schema descriptor for played_at field.
	playhistoryDescPlayedAt := playhistoryFields[0].Descriptor()
	// playhistory.DefaultPlayedAt holds the default value on creation for the played_at field.
	playhistory.DefaultPlayedAt = playhistoryDescPlayedAt.Default.(func() time.Time)
	// playhistoryDescProgressSeconds is the schema descriptor for progress_seconds field.
	playhistoryDescProgressSeconds := playhistoryFields[1].Descriptor()
	// playhistory.DefaultProgressSeconds holds the default value on creation for the progress_seconds field.
	playhistory.DefaultProgressSeconds = playhistoryDescProgressSeconds.Default.(float64)
	// playhistoryDescDurationSeconds is the schema descriptor for duration_seconds field.
	playhistoryDescDurationSeconds := playhistoryFields[2].Descriptor()
	// playhistory.DefaultDurationSeconds holds the default value on creation for the duration_seconds field.
	playhistory.DefaultDurationSeconds = playhistoryDescDurationSeconds.Default.(float64)
	// playhistoryDescCompleted is the schema descriptor for completed field.
	playhistoryDescCompleted := playhistoryFields[3].Descriptor()
	// playhistory.DefaultCompleted holds the default value on creation for the completed field.
	playhistory.DefaultCompleted = playhistoryDescCompleted.Default.(bool)
	// playhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	playhistoryDescUpdatedAt := playhistoryFields[4].Descriptor()
	// playhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playhistory.DefaultUpdatedAt = playhistoryDescUpdatedAt.Default.(func() time.Time)
	// playhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playhistory.UpdateDefaultUpdatedAt = playhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescName is the schema descriptor for name field.
	playlistDescName := playlistFields[0].Descriptor()
	// playlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	playlist.NameValidator = playlistDescName.Validators[0].(func(string) error)
	// playlistDescDescription is the schema descriptor for description field.
	playlistDescDescription := playlistFields[1].Descriptor()
	// playlist.DefaultDescription holds the default value on creation for the description field.
	playlist.DefaultDescription = playlistDescDescription.Default.(string)
	// playlistDescCoverTheme is the schema descriptor for cover_theme field.
	playlistDescCoverTheme := playlistFields[2].Descriptor()
	// playlist.DefaultCoverTheme holds the default value on creation for the cover_theme field.
	playlist.DefaultCoverTheme = playlistDescCoverTheme.Default.(string)
	// playlistDescFavorite is the schema descriptor for favorite field.
	playlistDescFavorite := playlistFields[3].Descriptor()
	// playlist.DefaultFavorite holds the default value on creation for the favorite field.
	playlist.DefaultFavorite = playlistDescFavorite.Default.(bool)
	// playlistDescCreatedAt is the schema descriptor for created_at field.
	playlistDescCreatedAt := playlistFields[4].Descriptor()
	// playlist.DefaultCreatedAt holds the default value on creation for the created_at field.
	playlist.DefaultCreatedAt = playlistDescCreatedAt.Default.(func() time.Time)
	// playlistDescUpdatedAt is the schema descriptor for updated_at field.
	playlistDescUpdatedAt := playlistFields[5].Descriptor()
	// playlist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playlist.DefaultUpdatedAt = playlistDescUpdatedAt.Default.(func() time.Time)
	// playlist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playlist.UpdateDefaultUpdatedAt = playlistDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[2].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescTitle is the schema descriptor for title field.
	songDescTitle := songFields[0].Descriptor()
	// song.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	song.TitleValidator = songDescTitle.Validators[0].(func(string) error)
	// songDescPath is the schema descriptor for path field.
	songDescPath := songFields[1].Descriptor()
	// song.PathValidator is a validator for the "path" field. It is called by the builders before save.
	song.PathValidator = songDescPath.Validators[0].(func(string) error)
	// songDescFileName is the schema descriptor for file_name field.
	songDescFileName := songFields[2].Descriptor()
	// song.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	song.FileNameValidator = songDescFileName.Validators[0].(func(string) error)
	// songDescFormat is the schema descriptor for format field.
	songDescFormat := songFields[3].Descriptor()
	// song.DefaultFormat holds the default value on creation for the format field.
	song.DefaultFormat = songDescFormat.Default.(string)
	// songDescMime is the schema descriptor for mime field.
	songDescMime := songFields[4].Descriptor()
	// song.DefaultMime holds the default value on creation for the mime field.
	song.DefaultMime = songDescMime.Default.(string)
	// songDescSizeBytes is the schema descriptor for size_bytes field.
	songDescSizeBytes := songFields[5].Descriptor()
	// song.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	song.DefaultSizeBytes = songDescSizeBytes.Default.(int64)
	// songDescModTimeUnixNano is the schema descriptor for mod_time_unix_nano field.
	songDescModTimeUnixNano := songFields[6].Descriptor()
	// song.DefaultModTimeUnixNano holds the default value on creation for the mod_time_unix_nano field.
	song.DefaultModTimeUnixNano = songDescModTimeUnixNano.Default.(int64)
	// songDescContentHash is the schema descriptor for content_hash field.
	songDescContentHash := songFields[7].Descriptor()
	// song.DefaultContentHash holds the default value on creation for the content_hash field.
	song.DefaultContentHash = songDescContentHash.Default.(string)
	// songDescDurationSeconds is the schema descriptor for duration_seconds field.
	songDescDurationSeconds := songFields[8].Descriptor()
	// song.DefaultDurationSeconds holds the default value on creation for the duration_seconds field.
	song.DefaultDurationSeconds = songDescDurationSeconds.Default.(float64)
	// songDescSampleRate is the schema descriptor for sample_rate field.
	songDescSampleRate := songFields[9].Descriptor()
	// song.DefaultSampleRate holds the default value on creation for the sample_rate field.
	song.DefaultSampleRate = songDescSampleRate.Default.(int)
	// songDescBitRate is the schema descriptor for bit_rate field.
	songDescBitRate := songFields[10].Descriptor()
	// song.DefaultBitRate holds the default value on creation for the bit_rate field.
	song.DefaultBitRate = songDescBitRate.Default.(int)
	// songDescBitDepth is the schema descriptor for bit_depth field.
	songDescBitDepth := songFields[11].Descriptor()
	// song.DefaultBitDepth holds the default value on creation for the bit_depth field.
	song.DefaultBitDepth = songDescBitDepth.Default.(int)
	// songDescYear is the schema descriptor for year field.
	songDescYear := songFields[12].Descriptor()
	// song.DefaultYear holds the default value on creation for the year field.
	song.DefaultYear = songDescYear.Default.(int)
	// songDescLyricsEmbedded is the schema descriptor for lyrics_embedded field.
	songDescLyricsEmbedded := songFields[13].Descriptor()
	// song.DefaultLyricsEmbedded holds the default value on creation for the lyrics_embedded field.
	song.DefaultLyricsEmbedded = songDescLyricsEmbedded.Default.(string)
	// songDescLyricsSource is the schema descriptor for lyrics_source field.
	songDescLyricsSource := songFields[14].Descriptor()
	// song.DefaultLyricsSource holds the default value on creation for the lyrics_source field.
	song.DefaultLyricsSource = songDescLyricsSource.Default.(string)
	// songDescNeteaseID is the schema descriptor for netease_id field.
	songDescNeteaseID := songFields[15].Descriptor()
	// song.DefaultNeteaseID holds the default value on creation for the netease_id field.
	song.DefaultNeteaseID = songDescNeteaseID.Default.(string)
	// songDescFavorite is the schema descriptor for favorite field.
	songDescFavorite := songFields[16].Descriptor()
	// song.DefaultFavorite holds the default value on creation for the favorite field.
	song.DefaultFavorite = songDescFavorite.Default.(bool)
	// songDescPlayCount is the schema descriptor for play_count field.
	songDescPlayCount := songFields[17].Descriptor()
	// song.DefaultPlayCount holds the default value on creation for the play_count field.
	song.DefaultPlayCount = songDescPlayCount.Default.(int)
	// songDescCreatedAt is the schema descriptor for created_at field.
	songDescCreatedAt := songFields[19].Descriptor()
	// song.DefaultCreatedAt holds the default value on creation for the created_at field.
	song.DefaultCreatedAt = songDescCreatedAt.Default.(func() time.Time)
	// songDescUpdatedAt is the schema descriptor for updated_at field.
	songDescUpdatedAt := songFields[20].Descriptor()
	// song.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	song.DefaultUpdatedAt = songDescUpdatedAt.Default.(func() time.Time)
	// song.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	song.UpdateDefaultUpdatedAt = songDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[3].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescAvatarDataURL is the schema descriptor for avatar_data_url field.
	userDescAvatarDataURL := userFields[4].Descriptor()
	// user.DefaultAvatarDataURL holds the default value on creation for the avatar_data_url field.
	user.DefaultAvatarDataURL = userDescAvatarDataURL.Default.(string)
	// userDescMcpTokenHash is the schema descriptor for mcp_token_hash field.
	userDescMcpTokenHash := userFields[5].Descriptor()
	// user.DefaultMcpTokenHash holds the default value on creation for the mcp_token_hash field.
	user.DefaultMcpTokenHash = userDescMcpTokenHash.Default.(string)
	// userDescMcpTokenHint is the schema descriptor for mcp_token_hint field.
	userDescMcpTokenHint := userFields[6].Descriptor()
	// user.DefaultMcpTokenHint holds the default value on creation for the mcp_token_hint field.
	user.DefaultMcpTokenHint = userDescMcpTokenHint.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	useralbumfavoriteFields := schema.UserAlbumFavorite{}.Fields()
	_ = useralbumfavoriteFields
	// useralbumfavoriteDescCreatedAt is the schema descriptor for created_at field.
	useralbumfavoriteDescCreatedAt := useralbumfavoriteFields[0].Descriptor()
	// useralbumfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	useralbumfavorite.DefaultCreatedAt = useralbumfavoriteDescCreatedAt.Default.(func() time.Time)
	userartistfavoriteFields := schema.UserArtistFavorite{}.Fields()
	_ = userartistfavoriteFields
	// userartistfavoriteDescCreatedAt is the schema descriptor for created_at field.
	userartistfavoriteDescCreatedAt := userartistfavoriteFields[0].Descriptor()
	// userartistfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	userartistfavorite.DefaultCreatedAt = userartistfavoriteDescCreatedAt.Default.(func() time.Time)
	userradiofavoriteFields := schema.UserRadioFavorite{}.Fields()
	_ = userradiofavoriteFields
	// userradiofavoriteDescStationID is the schema descriptor for station_id field.
	userradiofavoriteDescStationID := userradiofavoriteFields[0].Descriptor()
	// userradiofavorite.StationIDValidator is a validator for the "station_id" field. It is called by the builders before save.
	userradiofavorite.StationIDValidator = userradiofavoriteDescStationID.Validators[0].(func(string) error)
	// userradiofavoriteDescName is the schema descriptor for name field.
	userradiofavoriteDescName := userradiofavoriteFields[1].Descriptor()
	// userradiofavorite.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userradiofavorite.NameValidator = userradiofavoriteDescName.Validators[0].(func(string) error)
	// userradiofavoriteDescURL is the schema descriptor for url field.
	userradiofavoriteDescURL := userradiofavoriteFields[2].Descriptor()
	// userradiofavorite.URLValidator is a validator for the "url" field. It is called by the builders before save.
	userradiofavorite.URLValidator = userradiofavoriteDescURL.Validators[0].(func(string) error)
	// userradiofavoriteDescSourceURL is the schema descriptor for source_url field.
	userradiofavoriteDescSourceURL := userradiofavoriteFields[3].Descriptor()
	// userradiofavorite.DefaultSourceURL holds the default value on creation for the source_url field.
	userradiofavorite.DefaultSourceURL = userradiofavoriteDescSourceURL.Default.(string)
	// userradiofavoriteDescGroupName is the schema descriptor for group_name field.
	userradiofavoriteDescGroupName := userradiofavoriteFields[4].Descriptor()
	// userradiofavorite.DefaultGroupName holds the default value on creation for the group_name field.
	userradiofavorite.DefaultGroupName = userradiofavoriteDescGroupName.Default.(string)
	// userradiofavoriteDescCountry is the schema descriptor for country field.
	userradiofavoriteDescCountry := userradiofavoriteFields[5].Descriptor()
	// userradiofavorite.DefaultCountry holds the default value on creation for the country field.
	userradiofavorite.DefaultCountry = userradiofavoriteDescCountry.Default.(string)
	// userradiofavoriteDescTags is the schema descriptor for tags field.
	userradiofavoriteDescTags := userradiofavoriteFields[6].Descriptor()
	// userradiofavorite.DefaultTags holds the default value on creation for the tags field.
	userradiofavorite.DefaultTags = userradiofavoriteDescTags.Default.(string)
	// userradiofavoriteDescCodec is the schema descriptor for codec field.
	userradiofavoriteDescCodec := userradiofavoriteFields[7].Descriptor()
	// userradiofavorite.DefaultCodec holds the default value on creation for the codec field.
	userradiofavorite.DefaultCodec = userradiofavoriteDescCodec.Default.(string)
	// userradiofavoriteDescBitrate is the schema descriptor for bitrate field.
	userradiofavoriteDescBitrate := userradiofavoriteFields[8].Descriptor()
	// userradiofavorite.DefaultBitrate holds the default value on creation for the bitrate field.
	userradiofavorite.DefaultBitrate = userradiofavoriteDescBitrate.Default.(int)
	// userradiofavoriteDescHomepage is the schema descriptor for homepage field.
	userradiofavoriteDescHomepage := userradiofavoriteFields[9].Descriptor()
	// userradiofavorite.DefaultHomepage holds the default value on creation for the homepage field.
	userradiofavorite.DefaultHomepage = userradiofavoriteDescHomepage.Default.(string)
	// userradiofavoriteDescFavicon is the schema descriptor for favicon field.
	userradiofavoriteDescFavicon := userradiofavoriteFields[10].Descriptor()
	// userradiofavorite.DefaultFavicon holds the default value on creation for the favicon field.
	userradiofavorite.DefaultFavicon = userradiofavoriteDescFavicon.Default.(string)
	// userradiofavoriteDescCreatedAt is the schema descriptor for created_at field.
	userradiofavoriteDescCreatedAt := userradiofavoriteFields[11].Descriptor()
	// userradiofavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	userradiofavorite.DefaultCreatedAt = userradiofavoriteDescCreatedAt.Default.(func() time.Time)
	usersongfavoriteFields := schema.UserSongFavorite{}.Fields()
	_ = usersongfavoriteFields
	// usersongfavoriteDescCreatedAt is the schema descriptor for created_at field.
	usersongfavoriteDescCreatedAt := usersongfavoriteFields[0].Descriptor()
	// usersongfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersongfavorite.DefaultCreatedAt = usersongfavoriteDescCreatedAt.Default.(func() time.Time)
}
