// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lark/backend/ent/album"
	"lark/backend/ent/appsetting"
	"lark/backend/ent/artist"
	"lark/backend/ent/candidatecache"
	"lark/backend/ent/librarydirectory"
	"lark/backend/ent/playhistory"
	"lark/backend/ent/playlist"
	"lark/backend/ent/plugin"
	"lark/backend/ent/pluginstorage"
	"lark/backend/ent/schema"
	"lark/backend/ent/session"
	"lark/backend/ent/song"
	"lark/backend/ent/user"
	"lark/backend/ent/useralbumfavorite"
	"lark/backend/ent/userartistfavorite"
	"lark/backend/ent/userradiofavorite"
	"lark/backend/ent/usersongfavorite"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescTitle is the schema descriptor for title field.
	albumDescTitle := albumFields[0].Descriptor()
	// album.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	album.TitleValidator = albumDescTitle.Validators[0].(func(string) error)
	// albumDescAlbumArtist is the schema descriptor for album_artist field.
	albumDescAlbumArtist := albumFields[1].Descriptor()
	// album.DefaultAlbumArtist holds the default value on creation for the album_artist field.
	album.DefaultAlbumArtist = albumDescAlbumArtist.Default.(string)
	// albumDescCoverPath is the schema descriptor for cover_path field.
	albumDescCoverPath := albumFields[2].Descriptor()
	// album.DefaultCoverPath holds the default value on creation for the cover_path field.
	album.DefaultCoverPath = albumDescCoverPath.Default.(string)
	// albumDescYear is the schema descriptor for year field.
	albumDescYear := albumFields[3].Descriptor()
	// album.DefaultYear holds the default value on creation for the year field.
	album.DefaultYear = albumDescYear.Default.(int)
	// albumDescFavorite is the schema descriptor for favorite field.
	albumDescFavorite := albumFields[4].Descriptor()
	// album.DefaultFavorite holds the default value on creation for the favorite field.
	album.DefaultFavorite = albumDescFavorite.Default.(bool)
	// albumDescCreatedAt is the schema descriptor for created_at field.
	albumDescCreatedAt := albumFields[5].Descriptor()
	// album.DefaultCreatedAt holds the default value on creation for the created_at field.
	album.DefaultCreatedAt = albumDescCreatedAt.Default.(func() time.Time)
	// albumDescUpdatedAt is the schema descriptor for updated_at field.
	albumDescUpdatedAt := albumFields[6].Descriptor()
	// album.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	album.DefaultUpdatedAt = albumDescUpdatedAt.Default.(func() time.Time)
	// album.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	album.UpdateDefaultUpdatedAt = albumDescUpdatedAt.UpdateDefault.(func() time.Time)
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescKey is the schema descriptor for key field.
	appsettingDescKey := appsettingFields[0].Descriptor()
	// appsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	appsetting.KeyValidator = appsettingDescKey.Validators[0].(func(string) error)
	// appsettingDescValue is the schema descriptor for value field.
	appsettingDescValue := appsettingFields[1].Descriptor()
	// appsetting.DefaultValue holds the default value on creation for the value field.
	appsetting.DefaultValue = appsettingDescValue.Default.(string)
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingFields[2].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingFields[3].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	artistFields := schema.Artist{}.Fields()
	_ = artistFields
	// artistDescName is the schema descriptor for name field.
	artistDescName := artistFields[0].Descriptor()
	// artist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artist.NameValidator = artistDescName.Validators[0].(func(string) error)
	// artistDescInitial is the schema descriptor for initial field.
	artistDescInitial := artistFields[1].Descriptor()
	// artist.DefaultInitial holds the default value on creation for the initial field.
	artist.DefaultInitial = artistDescInitial.Default.(string)
	// artist.InitialValidator is a validator for the "initial" field. It is called by the builders before save.
	artist.InitialValidator = artistDescInitial.Validators[0].(func(string) error)
	// artistDescCreatedAt is the schema descriptor for created_at field.
	artistDescCreatedAt := artistFields[2].Descriptor()
	// artist.DefaultCreatedAt holds the default value on creation for the created_at field.
	artist.DefaultCreatedAt = artistDescCreatedAt.Default.(func() time.Time)
	// artistDescUpdatedAt is the schema descriptor for updated_at field.
	artistDescUpdatedAt := artistFields[3].Descriptor()
	// artist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	artist.DefaultUpdatedAt = artistDescUpdatedAt.Default.(func() time.Time)
	// artist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	artist.UpdateDefaultUpdatedAt = artistDescUpdatedAt.UpdateDefault.(func() time.Time)
	candidatecacheFields := schema.CandidateCache{}.Fields()
	_ = candidatecacheFields
	// candidatecacheDescTargetType is the schema descriptor for target_type field.
	candidatecacheDescTargetType := candidatecacheFields[1].Descriptor()
	// candidatecache.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	candidatecache.TargetTypeValidator = candidatecacheDescTargetType.Validators[0].(func(string) error)
	// candidatecacheDescQueryKind is the schema descriptor for query_kind field.
	candidatecacheDescQueryKind := candidatecacheFields[3].Descriptor()
	// candidatecache.QueryKindValidator is a validator for the "query_kind" field. It is called by the builders before save.
	candidatecache.QueryKindValidator = candidatecacheDescQueryKind.Validators[0].(func(string) error)
	// candidatecacheDescSnapshotHash is the schema descriptor for snapshot_hash field.
	candidatecacheDescSnapshotHash := candidatecacheFields[4].Descriptor()
	// candidatecache.SnapshotHashValidator is a validator for the "snapshot_hash" field. It is called by the builders before save.
	candidatecache.SnapshotHashValidator = candidatecacheDescSnapshotHash.Validators[0].(func(string) error)
	// candidatecacheDescPayload is the schema descriptor for payload field.
	candidatecacheDescPayload := candidatecacheFields[5].Descriptor()
	// candidatecache.DefaultPayload holds the default value on creation for the payload field.
	candidatecache.DefaultPayload = candidatecacheDescPayload.Default.(string)
	// candidatecacheDescCreatedAt is the schema descriptor for created_at field.
	candidatecacheDescCreatedAt := candidatecacheFields[7].Descriptor()
	// candidatecache.DefaultCreatedAt holds the default value on creation for the created_at field.
	candidatecache.DefaultCreatedAt = candidatecacheDescCreatedAt.Default.(func() time.Time)
	// candidatecacheDescUpdatedAt is the schema descriptor for updated_at field.
	candidatecacheDescUpdatedAt := candidatecacheFields[8].Descriptor()
	// candidatecache.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	candidatecache.DefaultUpdatedAt = candidatecacheDescUpdatedAt.Default.(func() time.Time)
	// candidatecache.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	candidatecache.UpdateDefaultUpdatedAt = candidatecacheDescUpdatedAt.UpdateDefault.(func() time.Time)
	librarydirectoryFields := schema.LibraryDirectory{}.Fields()
	_ = librarydirectoryFields
	// librarydirectoryDescPath is the schema descriptor for path field.
	librarydirectoryDescPath := librarydirectoryFields[0].Descriptor()
	// librarydirectory.PathValidator is a validator for the "path" field. It is called by the builders before save.
	librarydirectory.PathValidator = librarydirectoryDescPath.Validators[0].(func(string) error)
	// librarydirectoryDescNote is the schema descriptor for note field.
	librarydirectoryDescNote := librarydirectoryFields[1].Descriptor()
	// librarydirectory.DefaultNote holds the default value on creation for the note field.
	librarydirectory.DefaultNote = librarydirectoryDescNote.Default.(string)
	// librarydirectoryDescWatchEnabled is the schema descriptor for watch_enabled field.
	librarydirectoryDescWatchEnabled := librarydirectoryFields[2].Descriptor()
	// librarydirectory.DefaultWatchEnabled holds the default value on creation for the watch_enabled field.
	librarydirectory.DefaultWatchEnabled = librarydirectoryDescWatchEnabled.Default.(bool)
	// librarydirectoryDescCreatedAt is the schema descriptor for created_at field.
	librarydirectoryDescCreatedAt := librarydirectoryFields[3].Descriptor()
	// librarydirectory.DefaultCreatedAt holds the default value on creation for the created_at field.
	librarydirectory.DefaultCreatedAt = librarydirectoryDescCreatedAt.Default.(func() time.Time)
	// librarydirectoryDescUpdatedAt is the schema descriptor for updated_at field.
	librarydirectoryDescUpdatedAt := librarydirectoryFields[4].Descriptor()
	// librarydirectory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	librarydirectory.DefaultUpdatedAt = librarydirectoryDescUpdatedAt.Default.(func() time.Time)
	// librarydirectory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	librarydirectory.UpdateDefaultUpdatedAt = librarydirectoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	playhistoryFields := schema.PlayHistory{}.Fields()
	_ = playhistoryFields
	// playhistoryDescPlayedAt is the schema descriptor for played_at field.
	playhistoryDescPlayedAt := playhistoryFields[0].Descriptor()
	// playhistory.DefaultPlayedAt holds the default value on creation for the played_at field.
	playhistory.DefaultPlayedAt = playhistoryDescPlayedAt.Default.(func() time.Time)
	// playhistoryDescProgressSeconds is the schema descriptor for progress_seconds field.
	playhistoryDescProgressSeconds := playhistoryFields[1].Descriptor()
	// playhistory.DefaultProgressSeconds holds the default value on creation for the progress_seconds field.
	playhistory.DefaultProgressSeconds = playhistoryDescProgressSeconds.Default.(float64)
	// playhistoryDescDurationSeconds is the schema descriptor for duration_seconds field.
	playhistoryDescDurationSeconds := playhistoryFields[2].Descriptor()
	// playhistory.DefaultDurationSeconds holds the default value on creation for the duration_seconds field.
	playhistory.DefaultDurationSeconds = playhistoryDescDurationSeconds.Default.(float64)
	// playhistoryDescCompleted is the schema descriptor for completed field.
	playhistoryDescCompleted := playhistoryFields[3].Descriptor()
	// playhistory.DefaultCompleted holds the default value on creation for the completed field.
	playhistory.DefaultCompleted = playhistoryDescCompleted.Default.(bool)
	// playhistoryDescDeviceType is the schema descriptor for device_type field.
	playhistoryDescDeviceType := playhistoryFields[4].Descriptor()
	// playhistory.DefaultDeviceType holds the default value on creation for the device_type field.
	playhistory.DefaultDeviceType = playhistoryDescDeviceType.Default.(string)
	// playhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	playhistoryDescUpdatedAt := playhistoryFields[5].Descriptor()
	// playhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playhistory.DefaultUpdatedAt = playhistoryDescUpdatedAt.Default.(func() time.Time)
	// playhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playhistory.UpdateDefaultUpdatedAt = playhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescName is the schema descriptor for name field.
	playlistDescName := playlistFields[0].Descriptor()
	// playlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	playlist.NameValidator = playlistDescName.Validators[0].(func(string) error)
	// playlistDescDescription is the schema descriptor for description field.
	playlistDescDescription := playlistFields[1].Descriptor()
	// playlist.DefaultDescription holds the default value on creation for the description field.
	playlist.DefaultDescription = playlistDescDescription.Default.(string)
	// playlistDescCoverTheme is the schema descriptor for cover_theme field.
	playlistDescCoverTheme := playlistFields[2].Descriptor()
	// playlist.DefaultCoverTheme holds the default value on creation for the cover_theme field.
	playlist.DefaultCoverTheme = playlistDescCoverTheme.Default.(string)
	// playlistDescCoverURL is the schema descriptor for cover_url field.
	playlistDescCoverURL := playlistFields[3].Descriptor()
	// playlist.DefaultCoverURL holds the default value on creation for the cover_url field.
	playlist.DefaultCoverURL = playlistDescCoverURL.Default.(string)
	// playlistDescFavorite is the schema descriptor for favorite field.
	playlistDescFavorite := playlistFields[4].Descriptor()
	// playlist.DefaultFavorite holds the default value on creation for the favorite field.
	playlist.DefaultFavorite = playlistDescFavorite.Default.(bool)
	// playlistDescCreatedAt is the schema descriptor for created_at field.
	playlistDescCreatedAt := playlistFields[5].Descriptor()
	// playlist.DefaultCreatedAt holds the default value on creation for the created_at field.
	playlist.DefaultCreatedAt = playlistDescCreatedAt.Default.(func() time.Time)
	// playlistDescUpdatedAt is the schema descriptor for updated_at field.
	playlistDescUpdatedAt := playlistFields[6].Descriptor()
	// playlist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playlist.DefaultUpdatedAt = playlistDescUpdatedAt.Default.(func() time.Time)
	// playlist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playlist.UpdateDefaultUpdatedAt = playlistDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[0].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescVersion is the schema descriptor for version field.
	pluginDescVersion := pluginFields[1].Descriptor()
	// plugin.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	plugin.VersionValidator = pluginDescVersion.Validators[0].(func(string) error)
	// pluginDescDescription is the schema descriptor for description field.
	pluginDescDescription := pluginFields[2].Descriptor()
	// plugin.DefaultDescription holds the default value on creation for the description field.
	plugin.DefaultDescription = pluginDescDescription.Default.(string)
	// pluginDescAuthor is the schema descriptor for author field.
	pluginDescAuthor := pluginFields[3].Descriptor()
	// plugin.DefaultAuthor holds the default value on creation for the author field.
	plugin.DefaultAuthor = pluginDescAuthor.Default.(string)
	// pluginDescHomepage is the schema descriptor for homepage field.
	pluginDescHomepage := pluginFields[4].Descriptor()
	// plugin.DefaultHomepage holds the default value on creation for the homepage field.
	plugin.DefaultHomepage = pluginDescHomepage.Default.(string)
	// pluginDescLicense is the schema descriptor for license field.
	pluginDescLicense := pluginFields[5].Descriptor()
	// plugin.DefaultLicense holds the default value on creation for the license field.
	plugin.DefaultLicense = pluginDescLicense.Default.(string)
	// pluginDescEntryPath is the schema descriptor for entry_path field.
	pluginDescEntryPath := pluginFields[6].Descriptor()
	// plugin.EntryPathValidator is a validator for the "entry_path" field. It is called by the builders before save.
	plugin.EntryPathValidator = pluginDescEntryPath.Validators[0].(func(string) error)
	// pluginDescMain is the schema descriptor for main field.
	pluginDescMain := pluginFields[7].Descriptor()
	// plugin.MainValidator is a validator for the "main" field. It is called by the builders before save.
	plugin.MainValidator = pluginDescMain.Validators[0].(func(string) error)
	// pluginDescMinHostVersion is the schema descriptor for min_host_version field.
	pluginDescMinHostVersion := pluginFields[8].Descriptor()
	// plugin.DefaultMinHostVersion holds the default value on creation for the min_host_version field.
	plugin.DefaultMinHostVersion = pluginDescMinHostVersion.Default.(string)
	// pluginDescIcon is the schema descriptor for icon field.
	pluginDescIcon := pluginFields[12].Descriptor()
	// plugin.DefaultIcon holds the default value on creation for the icon field.
	plugin.DefaultIcon = pluginDescIcon.Default.(string)
	// pluginDescUpdateURL is the schema descriptor for update_url field.
	pluginDescUpdateURL := pluginFields[13].Descriptor()
	// plugin.DefaultUpdateURL holds the default value on creation for the update_url field.
	plugin.DefaultUpdateURL = pluginDescUpdateURL.Default.(string)
	// pluginDescDownloadURL is the schema descriptor for download_url field.
	pluginDescDownloadURL := pluginFields[14].Descriptor()
	// plugin.DefaultDownloadURL holds the default value on creation for the download_url field.
	plugin.DefaultDownloadURL = pluginDescDownloadURL.Default.(string)
	// pluginDescRenderEngine is the schema descriptor for render_engine field.
	pluginDescRenderEngine := pluginFields[15].Descriptor()
	// plugin.DefaultRenderEngine holds the default value on creation for the render_engine field.
	plugin.DefaultRenderEngine = pluginDescRenderEngine.Default.(string)
	// pluginDescStatus is the schema descriptor for status field.
	pluginDescStatus := pluginFields[16].Descriptor()
	// plugin.DefaultStatus holds the default value on creation for the status field.
	plugin.DefaultStatus = pluginDescStatus.Default.(string)
	// pluginDescZipHash is the schema descriptor for zip_hash field.
	pluginDescZipHash := pluginFields[17].Descriptor()
	// plugin.DefaultZipHash holds the default value on creation for the zip_hash field.
	plugin.DefaultZipHash = pluginDescZipHash.Default.(string)
	// pluginDescEntryHash is the schema descriptor for entry_hash field.
	pluginDescEntryHash := pluginFields[18].Descriptor()
	// plugin.DefaultEntryHash holds the default value on creation for the entry_hash field.
	plugin.DefaultEntryHash = pluginDescEntryHash.Default.(string)
	// pluginDescFileModTime is the schema descriptor for file_mod_time field.
	pluginDescFileModTime := pluginFields[19].Descriptor()
	// plugin.DefaultFileModTime holds the default value on creation for the file_mod_time field.
	plugin.DefaultFileModTime = pluginDescFileModTime.Default.(string)
	// pluginDescFilePath is the schema descriptor for file_path field.
	pluginDescFilePath := pluginFields[20].Descriptor()
	// plugin.DefaultFilePath holds the default value on creation for the file_path field.
	plugin.DefaultFilePath = pluginDescFilePath.Default.(string)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[21].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[22].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginstorageFields := schema.PluginStorage{}.Fields()
	_ = pluginstorageFields
	// pluginstorageDescPluginEntryPath is the schema descriptor for plugin_entry_path field.
	pluginstorageDescPluginEntryPath := pluginstorageFields[0].Descriptor()
	// pluginstorage.PluginEntryPathValidator is a validator for the "plugin_entry_path" field. It is called by the builders before save.
	pluginstorage.PluginEntryPathValidator = pluginstorageDescPluginEntryPath.Validators[0].(func(string) error)
	// pluginstorageDescNamespace is the schema descriptor for namespace field.
	pluginstorageDescNamespace := pluginstorageFields[1].Descriptor()
	// pluginstorage.NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	pluginstorage.NamespaceValidator = pluginstorageDescNamespace.Validators[0].(func(string) error)
	// pluginstorageDescKey is the schema descriptor for key field.
	pluginstorageDescKey := pluginstorageFields[2].Descriptor()
	// pluginstorage.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	pluginstorage.KeyValidator = pluginstorageDescKey.Validators[0].(func(string) error)
	// pluginstorageDescValue is the schema descriptor for value field.
	pluginstorageDescValue := pluginstorageFields[3].Descriptor()
	// pluginstorage.DefaultValue holds the default value on creation for the value field.
	pluginstorage.DefaultValue = pluginstorageDescValue.Default.(string)
	// pluginstorageDescCreatedAt is the schema descriptor for created_at field.
	pluginstorageDescCreatedAt := pluginstorageFields[4].Descriptor()
	// pluginstorage.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginstorage.DefaultCreatedAt = pluginstorageDescCreatedAt.Default.(func() time.Time)
	// pluginstorageDescUpdatedAt is the schema descriptor for updated_at field.
	pluginstorageDescUpdatedAt := pluginstorageFields[5].Descriptor()
	// pluginstorage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginstorage.DefaultUpdatedAt = pluginstorageDescUpdatedAt.Default.(func() time.Time)
	// pluginstorage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginstorage.UpdateDefaultUpdatedAt = pluginstorageDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[2].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescTitle is the schema descriptor for title field.
	songDescTitle := songFields[0].Descriptor()
	// song.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	song.TitleValidator = songDescTitle.Validators[0].(func(string) error)
	// songDescSourceType is the schema descriptor for source_type field.
	songDescSourceType := songFields[1].Descriptor()
	// song.DefaultSourceType holds the default value on creation for the source_type field.
	song.DefaultSourceType = songDescSourceType.Default.(string)
	// songDescSourceArtist is the schema descriptor for source_artist field.
	songDescSourceArtist := songFields[2].Descriptor()
	// song.DefaultSourceArtist holds the default value on creation for the source_artist field.
	song.DefaultSourceArtist = songDescSourceArtist.Default.(string)
	// songDescSourceAlbum is the schema descriptor for source_album field.
	songDescSourceAlbum := songFields[3].Descriptor()
	// song.DefaultSourceAlbum holds the default value on creation for the source_album field.
	song.DefaultSourceAlbum = songDescSourceAlbum.Default.(string)
	// songDescPath is the schema descriptor for path field.
	songDescPath := songFields[4].Descriptor()
	// song.PathValidator is a validator for the "path" field. It is called by the builders before save.
	song.PathValidator = songDescPath.Validators[0].(func(string) error)
	// songDescFileName is the schema descriptor for file_name field.
	songDescFileName := songFields[5].Descriptor()
	// song.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	song.FileNameValidator = songDescFileName.Validators[0].(func(string) error)
	// songDescFormat is the schema descriptor for format field.
	songDescFormat := songFields[6].Descriptor()
	// song.DefaultFormat holds the default value on creation for the format field.
	song.DefaultFormat = songDescFormat.Default.(string)
	// songDescMime is the schema descriptor for mime field.
	songDescMime := songFields[7].Descriptor()
	// song.DefaultMime holds the default value on creation for the mime field.
	song.DefaultMime = songDescMime.Default.(string)
	// songDescSizeBytes is the schema descriptor for size_bytes field.
	songDescSizeBytes := songFields[8].Descriptor()
	// song.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	song.DefaultSizeBytes = songDescSizeBytes.Default.(int64)
	// songDescModTimeUnixNano is the schema descriptor for mod_time_unix_nano field.
	songDescModTimeUnixNano := songFields[9].Descriptor()
	// song.DefaultModTimeUnixNano holds the default value on creation for the mod_time_unix_nano field.
	song.DefaultModTimeUnixNano = songDescModTimeUnixNano.Default.(int64)
	// songDescContentHash is the schema descriptor for content_hash field.
	songDescContentHash := songFields[10].Descriptor()
	// song.DefaultContentHash holds the default value on creation for the content_hash field.
	song.DefaultContentHash = songDescContentHash.Default.(string)
	// songDescURL is the schema descriptor for url field.
	songDescURL := songFields[11].Descriptor()
	// song.DefaultURL holds the default value on creation for the url field.
	song.DefaultURL = songDescURL.Default.(string)
	// songDescCoverURL is the schema descriptor for cover_url field.
	songDescCoverURL := songFields[12].Descriptor()
	// song.DefaultCoverURL holds the default value on creation for the cover_url field.
	song.DefaultCoverURL = songDescCoverURL.Default.(string)
	// songDescPluginEntryPath is the schema descriptor for plugin_entry_path field.
	songDescPluginEntryPath := songFields[13].Descriptor()
	// song.DefaultPluginEntryPath holds the default value on creation for the plugin_entry_path field.
	song.DefaultPluginEntryPath = songDescPluginEntryPath.Default.(string)
	// songDescSourceData is the schema descriptor for source_data field.
	songDescSourceData := songFields[14].Descriptor()
	// song.DefaultSourceData holds the default value on creation for the source_data field.
	song.DefaultSourceData = songDescSourceData.Default.(string)
	// songDescDedupKey is the schema descriptor for dedup_key field.
	songDescDedupKey := songFields[15].Descriptor()
	// song.DefaultDedupKey holds the default value on creation for the dedup_key field.
	song.DefaultDedupKey = songDescDedupKey.Default.(string)
	// songDescDurationSeconds is the schema descriptor for duration_seconds field.
	songDescDurationSeconds := songFields[16].Descriptor()
	// song.DefaultDurationSeconds holds the default value on creation for the duration_seconds field.
	song.DefaultDurationSeconds = songDescDurationSeconds.Default.(float64)
	// songDescSampleRate is the schema descriptor for sample_rate field.
	songDescSampleRate := songFields[17].Descriptor()
	// song.DefaultSampleRate holds the default value on creation for the sample_rate field.
	song.DefaultSampleRate = songDescSampleRate.Default.(int)
	// songDescBitRate is the schema descriptor for bit_rate field.
	songDescBitRate := songFields[18].Descriptor()
	// song.DefaultBitRate holds the default value on creation for the bit_rate field.
	song.DefaultBitRate = songDescBitRate.Default.(int)
	// songDescBitDepth is the schema descriptor for bit_depth field.
	songDescBitDepth := songFields[19].Descriptor()
	// song.DefaultBitDepth holds the default value on creation for the bit_depth field.
	song.DefaultBitDepth = songDescBitDepth.Default.(int)
	// songDescYear is the schema descriptor for year field.
	songDescYear := songFields[20].Descriptor()
	// song.DefaultYear holds the default value on creation for the year field.
	song.DefaultYear = songDescYear.Default.(int)
	// songDescGenre is the schema descriptor for genre field.
	songDescGenre := songFields[21].Descriptor()
	// song.DefaultGenre holds the default value on creation for the genre field.
	song.DefaultGenre = songDescGenre.Default.(string)
	// songDescLanguage is the schema descriptor for language field.
	songDescLanguage := songFields[22].Descriptor()
	// song.DefaultLanguage holds the default value on creation for the language field.
	song.DefaultLanguage = songDescLanguage.Default.(string)
	// songDescStyle is the schema descriptor for style field.
	songDescStyle := songFields[23].Descriptor()
	// song.DefaultStyle holds the default value on creation for the style field.
	song.DefaultStyle = songDescStyle.Default.(string)
	// songDescTrack is the schema descriptor for track field.
	songDescTrack := songFields[24].Descriptor()
	// song.DefaultTrack holds the default value on creation for the track field.
	song.DefaultTrack = songDescTrack.Default.(string)
	// songDescLyricsEmbedded is the schema descriptor for lyrics_embedded field.
	songDescLyricsEmbedded := songFields[25].Descriptor()
	// song.DefaultLyricsEmbedded holds the default value on creation for the lyrics_embedded field.
	song.DefaultLyricsEmbedded = songDescLyricsEmbedded.Default.(string)
	// songDescLyricsSource is the schema descriptor for lyrics_source field.
	songDescLyricsSource := songFields[26].Descriptor()
	// song.DefaultLyricsSource holds the default value on creation for the lyrics_source field.
	song.DefaultLyricsSource = songDescLyricsSource.Default.(string)
	// songDescLyricsRemoteURL is the schema descriptor for lyrics_remote_url field.
	songDescLyricsRemoteURL := songFields[27].Descriptor()
	// song.DefaultLyricsRemoteURL holds the default value on creation for the lyrics_remote_url field.
	song.DefaultLyricsRemoteURL = songDescLyricsRemoteURL.Default.(string)
	// songDescHasLyrics is the schema descriptor for has_lyrics field.
	songDescHasLyrics := songFields[28].Descriptor()
	// song.DefaultHasLyrics holds the default value on creation for the has_lyrics field.
	song.DefaultHasLyrics = songDescHasLyrics.Default.(bool)
	// songDescNeteaseID is the schema descriptor for netease_id field.
	songDescNeteaseID := songFields[29].Descriptor()
	// song.DefaultNeteaseID holds the default value on creation for the netease_id field.
	song.DefaultNeteaseID = songDescNeteaseID.Default.(string)
	// songDescIsLive is the schema descriptor for is_live field.
	songDescIsLive := songFields[30].Descriptor()
	// song.DefaultIsLive holds the default value on creation for the is_live field.
	song.DefaultIsLive = songDescIsLive.Default.(bool)
	// songDescIsVideo is the schema descriptor for is_video field.
	songDescIsVideo := songFields[31].Descriptor()
	// song.DefaultIsVideo holds the default value on creation for the is_video field.
	song.DefaultIsVideo = songDescIsVideo.Default.(bool)
	// songDescFavorite is the schema descriptor for favorite field.
	songDescFavorite := songFields[32].Descriptor()
	// song.DefaultFavorite holds the default value on creation for the favorite field.
	song.DefaultFavorite = songDescFavorite.Default.(bool)
	// songDescPlayCount is the schema descriptor for play_count field.
	songDescPlayCount := songFields[33].Descriptor()
	// song.DefaultPlayCount holds the default value on creation for the play_count field.
	song.DefaultPlayCount = songDescPlayCount.Default.(int)
	// songDescCreatedAt is the schema descriptor for created_at field.
	songDescCreatedAt := songFields[35].Descriptor()
	// song.DefaultCreatedAt holds the default value on creation for the created_at field.
	song.DefaultCreatedAt = songDescCreatedAt.Default.(func() time.Time)
	// songDescUpdatedAt is the schema descriptor for updated_at field.
	songDescUpdatedAt := songFields[36].Descriptor()
	// song.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	song.DefaultUpdatedAt = songDescUpdatedAt.Default.(func() time.Time)
	// song.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	song.UpdateDefaultUpdatedAt = songDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[3].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescAvatarDataURL is the schema descriptor for avatar_data_url field.
	userDescAvatarDataURL := userFields[4].Descriptor()
	// user.DefaultAvatarDataURL holds the default value on creation for the avatar_data_url field.
	user.DefaultAvatarDataURL = userDescAvatarDataURL.Default.(string)
	// userDescMcpTokenHash is the schema descriptor for mcp_token_hash field.
	userDescMcpTokenHash := userFields[5].Descriptor()
	// user.DefaultMcpTokenHash holds the default value on creation for the mcp_token_hash field.
	user.DefaultMcpTokenHash = userDescMcpTokenHash.Default.(string)
	// userDescMcpTokenHint is the schema descriptor for mcp_token_hint field.
	userDescMcpTokenHint := userFields[6].Descriptor()
	// user.DefaultMcpTokenHint holds the default value on creation for the mcp_token_hint field.
	user.DefaultMcpTokenHint = userDescMcpTokenHint.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	useralbumfavoriteFields := schema.UserAlbumFavorite{}.Fields()
	_ = useralbumfavoriteFields
	// useralbumfavoriteDescCreatedAt is the schema descriptor for created_at field.
	useralbumfavoriteDescCreatedAt := useralbumfavoriteFields[0].Descriptor()
	// useralbumfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	useralbumfavorite.DefaultCreatedAt = useralbumfavoriteDescCreatedAt.Default.(func() time.Time)
	userartistfavoriteFields := schema.UserArtistFavorite{}.Fields()
	_ = userartistfavoriteFields
	// userartistfavoriteDescCreatedAt is the schema descriptor for created_at field.
	userartistfavoriteDescCreatedAt := userartistfavoriteFields[0].Descriptor()
	// userartistfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	userartistfavorite.DefaultCreatedAt = userartistfavoriteDescCreatedAt.Default.(func() time.Time)
	userradiofavoriteFields := schema.UserRadioFavorite{}.Fields()
	_ = userradiofavoriteFields
	// userradiofavoriteDescStationID is the schema descriptor for station_id field.
	userradiofavoriteDescStationID := userradiofavoriteFields[0].Descriptor()
	// userradiofavorite.StationIDValidator is a validator for the "station_id" field. It is called by the builders before save.
	userradiofavorite.StationIDValidator = userradiofavoriteDescStationID.Validators[0].(func(string) error)
	// userradiofavoriteDescName is the schema descriptor for name field.
	userradiofavoriteDescName := userradiofavoriteFields[1].Descriptor()
	// userradiofavorite.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userradiofavorite.NameValidator = userradiofavoriteDescName.Validators[0].(func(string) error)
	// userradiofavoriteDescURL is the schema descriptor for url field.
	userradiofavoriteDescURL := userradiofavoriteFields[2].Descriptor()
	// userradiofavorite.URLValidator is a validator for the "url" field. It is called by the builders before save.
	userradiofavorite.URLValidator = userradiofavoriteDescURL.Validators[0].(func(string) error)
	// userradiofavoriteDescSourceURL is the schema descriptor for source_url field.
	userradiofavoriteDescSourceURL := userradiofavoriteFields[3].Descriptor()
	// userradiofavorite.DefaultSourceURL holds the default value on creation for the source_url field.
	userradiofavorite.DefaultSourceURL = userradiofavoriteDescSourceURL.Default.(string)
	// userradiofavoriteDescGroupName is the schema descriptor for group_name field.
	userradiofavoriteDescGroupName := userradiofavoriteFields[4].Descriptor()
	// userradiofavorite.DefaultGroupName holds the default value on creation for the group_name field.
	userradiofavorite.DefaultGroupName = userradiofavoriteDescGroupName.Default.(string)
	// userradiofavoriteDescCountry is the schema descriptor for country field.
	userradiofavoriteDescCountry := userradiofavoriteFields[5].Descriptor()
	// userradiofavorite.DefaultCountry holds the default value on creation for the country field.
	userradiofavorite.DefaultCountry = userradiofavoriteDescCountry.Default.(string)
	// userradiofavoriteDescTags is the schema descriptor for tags field.
	userradiofavoriteDescTags := userradiofavoriteFields[6].Descriptor()
	// userradiofavorite.DefaultTags holds the default value on creation for the tags field.
	userradiofavorite.DefaultTags = userradiofavoriteDescTags.Default.(string)
	// userradiofavoriteDescCodec is the schema descriptor for codec field.
	userradiofavoriteDescCodec := userradiofavoriteFields[7].Descriptor()
	// userradiofavorite.DefaultCodec holds the default value on creation for the codec field.
	userradiofavorite.DefaultCodec = userradiofavoriteDescCodec.Default.(string)
	// userradiofavoriteDescBitrate is the schema descriptor for bitrate field.
	userradiofavoriteDescBitrate := userradiofavoriteFields[8].Descriptor()
	// userradiofavorite.DefaultBitrate holds the default value on creation for the bitrate field.
	userradiofavorite.DefaultBitrate = userradiofavoriteDescBitrate.Default.(int)
	// userradiofavoriteDescHomepage is the schema descriptor for homepage field.
	userradiofavoriteDescHomepage := userradiofavoriteFields[9].Descriptor()
	// userradiofavorite.DefaultHomepage holds the default value on creation for the homepage field.
	userradiofavorite.DefaultHomepage = userradiofavoriteDescHomepage.Default.(string)
	// userradiofavoriteDescFavicon is the schema descriptor for favicon field.
	userradiofavoriteDescFavicon := userradiofavoriteFields[10].Descriptor()
	// userradiofavorite.DefaultFavicon holds the default value on creation for the favicon field.
	userradiofavorite.DefaultFavicon = userradiofavoriteDescFavicon.Default.(string)
	// userradiofavoriteDescCreatedAt is the schema descriptor for created_at field.
	userradiofavoriteDescCreatedAt := userradiofavoriteFields[11].Descriptor()
	// userradiofavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	userradiofavorite.DefaultCreatedAt = userradiofavoriteDescCreatedAt.Default.(func() time.Time)
	usersongfavoriteFields := schema.UserSongFavorite{}.Fields()
	_ = usersongfavoriteFields
	// usersongfavoriteDescCreatedAt is the schema descriptor for created_at field.
	usersongfavoriteDescCreatedAt := usersongfavoriteFields[0].Descriptor()
	// usersongfavorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersongfavorite.DefaultCreatedAt = usersongfavoriteDescCreatedAt.Default.(func() time.Time)
}
