// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/song"
	"lark/backend/ent/user"
	"lark/backend/ent/usersongfavorite"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSongFavoriteCreate is the builder for creating a UserSongFavorite entity.
type UserSongFavoriteCreate struct {
	config
	mutation *UserSongFavoriteMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSongFavoriteCreate) SetCreatedAt(v time.Time) *UserSongFavoriteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSongFavoriteCreate) SetNillableCreatedAt(v *time.Time) *UserSongFavoriteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserSongFavoriteCreate) SetUserID(id int) *UserSongFavoriteCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserSongFavoriteCreate) SetUser(v *User) *UserSongFavoriteCreate {
	return _c.SetUserID(v.ID)
}

// SetSongID sets the "song" edge to the Song entity by ID.
func (_c *UserSongFavoriteCreate) SetSongID(id int) *UserSongFavoriteCreate {
	_c.mutation.SetSongID(id)
	return _c
}

// SetSong sets the "song" edge to the Song entity.
func (_c *UserSongFavoriteCreate) SetSong(v *Song) *UserSongFavoriteCreate {
	return _c.SetSongID(v.ID)
}

// Mutation returns the UserSongFavoriteMutation object of the builder.
func (_c *UserSongFavoriteCreate) Mutation() *UserSongFavoriteMutation {
	return _c.mutation
}

// Save creates the UserSongFavorite in the database.
func (_c *UserSongFavoriteCreate) Save(ctx context.Context) (*UserSongFavorite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSongFavoriteCreate) SaveX(ctx context.Context) *UserSongFavorite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSongFavoriteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSongFavoriteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSongFavoriteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersongfavorite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSongFavoriteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSongFavorite.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserSongFavorite.user"`)}
	}
	if len(_c.mutation.SongIDs()) == 0 {
		return &ValidationError{Name: "song", err: errors.New(`ent: missing required edge "UserSongFavorite.song"`)}
	}
	return nil
}

func (_c *UserSongFavoriteCreate) sqlSave(ctx context.Context) (*UserSongFavorite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSongFavoriteCreate) createSpec() (*UserSongFavorite, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSongFavorite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersongfavorite.Table, sqlgraph.NewFieldSpec(usersongfavorite.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersongfavorite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersongfavorite.UserTable,
			Columns: []string{usersongfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_song_favorites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SongIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersongfavorite.SongTable,
			Columns: []string{usersongfavorite.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.song_user_favorites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserSongFavoriteCreateBulk is the builder for creating many UserSongFavorite entities in bulk.
type UserSongFavoriteCreateBulk struct {
	config
	err      error
	builders []*UserSongFavoriteCreate
}

// Save creates the UserSongFavorite entities in the database.
func (_c *UserSongFavoriteCreateBulk) Save(ctx context.Context) ([]*UserSongFavorite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSongFavorite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSongFavoriteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSongFavoriteCreateBulk) SaveX(ctx context.Context) []*UserSongFavorite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSongFavoriteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSongFavoriteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
