// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/artist"
	"lark/backend/ent/predicate"
	"lark/backend/ent/user"
	"lark/backend/ent/userartistfavorite"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserArtistFavoriteUpdate is the builder for updating UserArtistFavorite entities.
type UserArtistFavoriteUpdate struct {
	config
	hooks    []Hook
	mutation *UserArtistFavoriteMutation
}

// Where appends a list predicates to the UserArtistFavoriteUpdate builder.
func (_u *UserArtistFavoriteUpdate) Where(ps ...predicate.UserArtistFavorite) *UserArtistFavoriteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserArtistFavoriteUpdate) SetCreatedAt(v time.Time) *UserArtistFavoriteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserArtistFavoriteUpdate) SetNillableCreatedAt(v *time.Time) *UserArtistFavoriteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserArtistFavoriteUpdate) SetUserID(id int) *UserArtistFavoriteUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserArtistFavoriteUpdate) SetUser(v *User) *UserArtistFavoriteUpdate {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *UserArtistFavoriteUpdate) SetArtistID(id int) *UserArtistFavoriteUpdate {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *UserArtistFavoriteUpdate) SetArtist(v *Artist) *UserArtistFavoriteUpdate {
	return _u.SetArtistID(v.ID)
}

// Mutation returns the UserArtistFavoriteMutation object of the builder.
func (_u *UserArtistFavoriteUpdate) Mutation() *UserArtistFavoriteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserArtistFavoriteUpdate) ClearUser() *UserArtistFavoriteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *UserArtistFavoriteUpdate) ClearArtist() *UserArtistFavoriteUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserArtistFavoriteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserArtistFavoriteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserArtistFavoriteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserArtistFavoriteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserArtistFavoriteUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserArtistFavorite.user"`)
	}
	if _u.mutation.ArtistCleared() && len(_u.mutation.ArtistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserArtistFavorite.artist"`)
	}
	return nil
}

func (_u *UserArtistFavoriteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userartistfavorite.Table, userartistfavorite.Columns, sqlgraph.NewFieldSpec(userartistfavorite.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userartistfavorite.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.UserTable,
			Columns: []string{userartistfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.UserTable,
			Columns: []string{userartistfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.ArtistTable,
			Columns: []string{userartistfavorite.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.ArtistTable,
			Columns: []string{userartistfavorite.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userartistfavorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserArtistFavoriteUpdateOne is the builder for updating a single UserArtistFavorite entity.
type UserArtistFavoriteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserArtistFavoriteMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserArtistFavoriteUpdateOne) SetCreatedAt(v time.Time) *UserArtistFavoriteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserArtistFavoriteUpdateOne) SetNillableCreatedAt(v *time.Time) *UserArtistFavoriteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserArtistFavoriteUpdateOne) SetUserID(id int) *UserArtistFavoriteUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserArtistFavoriteUpdateOne) SetUser(v *User) *UserArtistFavoriteUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *UserArtistFavoriteUpdateOne) SetArtistID(id int) *UserArtistFavoriteUpdateOne {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *UserArtistFavoriteUpdateOne) SetArtist(v *Artist) *UserArtistFavoriteUpdateOne {
	return _u.SetArtistID(v.ID)
}

// Mutation returns the UserArtistFavoriteMutation object of the builder.
func (_u *UserArtistFavoriteUpdateOne) Mutation() *UserArtistFavoriteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserArtistFavoriteUpdateOne) ClearUser() *UserArtistFavoriteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *UserArtistFavoriteUpdateOne) ClearArtist() *UserArtistFavoriteUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// Where appends a list predicates to the UserArtistFavoriteUpdate builder.
func (_u *UserArtistFavoriteUpdateOne) Where(ps ...predicate.UserArtistFavorite) *UserArtistFavoriteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserArtistFavoriteUpdateOne) Select(field string, fields ...string) *UserArtistFavoriteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserArtistFavorite entity.
func (_u *UserArtistFavoriteUpdateOne) Save(ctx context.Context) (*UserArtistFavorite, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserArtistFavoriteUpdateOne) SaveX(ctx context.Context) *UserArtistFavorite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserArtistFavoriteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserArtistFavoriteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserArtistFavoriteUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserArtistFavorite.user"`)
	}
	if _u.mutation.ArtistCleared() && len(_u.mutation.ArtistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserArtistFavorite.artist"`)
	}
	return nil
}

func (_u *UserArtistFavoriteUpdateOne) sqlSave(ctx context.Context) (_node *UserArtistFavorite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userartistfavorite.Table, userartistfavorite.Columns, sqlgraph.NewFieldSpec(userartistfavorite.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserArtistFavorite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userartistfavorite.FieldID)
		for _, f := range fields {
			if !userartistfavorite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userartistfavorite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userartistfavorite.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.UserTable,
			Columns: []string{userartistfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.UserTable,
			Columns: []string{userartistfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.ArtistTable,
			Columns: []string{userartistfavorite.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userartistfavorite.ArtistTable,
			Columns: []string{userartistfavorite.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserArtistFavorite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userartistfavorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
