// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lark/backend/ent/album"
	"lark/backend/ent/user"
	"lark/backend/ent/useralbumfavorite"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAlbumFavoriteCreate is the builder for creating a UserAlbumFavorite entity.
type UserAlbumFavoriteCreate struct {
	config
	mutation *UserAlbumFavoriteMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAlbumFavoriteCreate) SetCreatedAt(v time.Time) *UserAlbumFavoriteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAlbumFavoriteCreate) SetNillableCreatedAt(v *time.Time) *UserAlbumFavoriteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserAlbumFavoriteCreate) SetUserID(id int) *UserAlbumFavoriteCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserAlbumFavoriteCreate) SetUser(v *User) *UserAlbumFavoriteCreate {
	return _c.SetUserID(v.ID)
}

// SetAlbumID sets the "album" edge to the Album entity by ID.
func (_c *UserAlbumFavoriteCreate) SetAlbumID(id int) *UserAlbumFavoriteCreate {
	_c.mutation.SetAlbumID(id)
	return _c
}

// SetAlbum sets the "album" edge to the Album entity.
func (_c *UserAlbumFavoriteCreate) SetAlbum(v *Album) *UserAlbumFavoriteCreate {
	return _c.SetAlbumID(v.ID)
}

// Mutation returns the UserAlbumFavoriteMutation object of the builder.
func (_c *UserAlbumFavoriteCreate) Mutation() *UserAlbumFavoriteMutation {
	return _c.mutation
}

// Save creates the UserAlbumFavorite in the database.
func (_c *UserAlbumFavoriteCreate) Save(ctx context.Context) (*UserAlbumFavorite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAlbumFavoriteCreate) SaveX(ctx context.Context) *UserAlbumFavorite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAlbumFavoriteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAlbumFavoriteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAlbumFavoriteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useralbumfavorite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAlbumFavoriteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAlbumFavorite.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserAlbumFavorite.user"`)}
	}
	if len(_c.mutation.AlbumIDs()) == 0 {
		return &ValidationError{Name: "album", err: errors.New(`ent: missing required edge "UserAlbumFavorite.album"`)}
	}
	return nil
}

func (_c *UserAlbumFavoriteCreate) sqlSave(ctx context.Context) (*UserAlbumFavorite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAlbumFavoriteCreate) createSpec() (*UserAlbumFavorite, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAlbumFavorite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useralbumfavorite.Table, sqlgraph.NewFieldSpec(useralbumfavorite.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useralbumfavorite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useralbumfavorite.UserTable,
			Columns: []string{useralbumfavorite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_album_favorites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useralbumfavorite.AlbumTable,
			Columns: []string{useralbumfavorite.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.album_user_favorites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserAlbumFavoriteCreateBulk is the builder for creating many UserAlbumFavorite entities in bulk.
type UserAlbumFavoriteCreateBulk struct {
	config
	err      error
	builders []*UserAlbumFavoriteCreate
}

// Save creates the UserAlbumFavorite entities in the database.
func (_c *UserAlbumFavoriteCreateBulk) Save(ctx context.Context) ([]*UserAlbumFavorite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAlbumFavorite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAlbumFavoriteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAlbumFavoriteCreateBulk) SaveX(ctx context.Context) []*UserAlbumFavorite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAlbumFavoriteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAlbumFavoriteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
