// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lark/backend/ent/predicate"
	"lark/backend/ent/usersongfavorite"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSongFavoriteDelete is the builder for deleting a UserSongFavorite entity.
type UserSongFavoriteDelete struct {
	config
	hooks    []Hook
	mutation *UserSongFavoriteMutation
}

// Where appends a list predicates to the UserSongFavoriteDelete builder.
func (_d *UserSongFavoriteDelete) Where(ps ...predicate.UserSongFavorite) *UserSongFavoriteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserSongFavoriteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSongFavoriteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserSongFavoriteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usersongfavorite.Table, sqlgraph.NewFieldSpec(usersongfavorite.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserSongFavoriteDeleteOne is the builder for deleting a single UserSongFavorite entity.
type UserSongFavoriteDeleteOne struct {
	_d *UserSongFavoriteDelete
}

// Where appends a list predicates to the UserSongFavoriteDelete builder.
func (_d *UserSongFavoriteDeleteOne) Where(ps ...predicate.UserSongFavorite) *UserSongFavoriteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserSongFavoriteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersongfavorite.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSongFavoriteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
