// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lark/backend/ent/artist"
	"lark/backend/ent/user"
	"lark/backend/ent/userartistfavorite"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserArtistFavorite is the model entity for the UserArtistFavorite schema.
type UserArtistFavorite struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserArtistFavoriteQuery when eager-loading is set.
	Edges                 UserArtistFavoriteEdges `json:"edges"`
	artist_user_favorites *int
	user_artist_favorites *int
	selectValues          sql.SelectValues
}

// UserArtistFavoriteEdges holds the relations/edges for other nodes in the graph.
type UserArtistFavoriteEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Artist holds the value of the artist edge.
	Artist *Artist `json:"artist,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserArtistFavoriteEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ArtistOrErr returns the Artist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserArtistFavoriteEdges) ArtistOrErr() (*Artist, error) {
	if e.Artist != nil {
		return e.Artist, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: artist.Label}
	}
	return nil, &NotLoadedError{edge: "artist"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserArtistFavorite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userartistfavorite.FieldID:
			values[i] = new(sql.NullInt64)
		case userartistfavorite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case userartistfavorite.ForeignKeys[0]: // artist_user_favorites
			values[i] = new(sql.NullInt64)
		case userartistfavorite.ForeignKeys[1]: // user_artist_favorites
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserArtistFavorite fields.
func (_m *UserArtistFavorite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userartistfavorite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userartistfavorite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userartistfavorite.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field artist_user_favorites", value)
			} else if value.Valid {
				_m.artist_user_favorites = new(int)
				*_m.artist_user_favorites = int(value.Int64)
			}
		case userartistfavorite.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_artist_favorites", value)
			} else if value.Valid {
				_m.user_artist_favorites = new(int)
				*_m.user_artist_favorites = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserArtistFavorite.
// This includes values selected through modifiers, order, etc.
func (_m *UserArtistFavorite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserArtistFavorite entity.
func (_m *UserArtistFavorite) QueryUser() *UserQuery {
	return NewUserArtistFavoriteClient(_m.config).QueryUser(_m)
}

// QueryArtist queries the "artist" edge of the UserArtistFavorite entity.
func (_m *UserArtistFavorite) QueryArtist() *ArtistQuery {
	return NewUserArtistFavoriteClient(_m.config).QueryArtist(_m)
}

// Update returns a builder for updating this UserArtistFavorite.
// Note that you need to call UserArtistFavorite.Unwrap() before calling this method if this UserArtistFavorite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserArtistFavorite) Update() *UserArtistFavoriteUpdateOne {
	return NewUserArtistFavoriteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserArtistFavorite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserArtistFavorite) Unwrap() *UserArtistFavorite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserArtistFavorite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserArtistFavorite) String() string {
	var builder strings.Builder
	builder.WriteString("UserArtistFavorite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserArtistFavorites is a parsable slice of UserArtistFavorite.
type UserArtistFavorites []*UserArtistFavorite
