// Code generated by ent, DO NOT EDIT.

package pluginstorage

import (
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldID, id))
}

// PluginEntryPath applies equality check predicate on the "plugin_entry_path" field. It's identical to PluginEntryPathEQ.
func PluginEntryPath(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldPluginEntryPath, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldNamespace, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldKey, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldUpdatedAt, v))
}

// PluginEntryPathEQ applies the EQ predicate on the "plugin_entry_path" field.
func PluginEntryPathEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldPluginEntryPath, v))
}

// PluginEntryPathNEQ applies the NEQ predicate on the "plugin_entry_path" field.
func PluginEntryPathNEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldPluginEntryPath, v))
}

// PluginEntryPathIn applies the In predicate on the "plugin_entry_path" field.
func PluginEntryPathIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldPluginEntryPath, vs...))
}

// PluginEntryPathNotIn applies the NotIn predicate on the "plugin_entry_path" field.
func PluginEntryPathNotIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldPluginEntryPath, vs...))
}

// PluginEntryPathGT applies the GT predicate on the "plugin_entry_path" field.
func PluginEntryPathGT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldPluginEntryPath, v))
}

// PluginEntryPathGTE applies the GTE predicate on the "plugin_entry_path" field.
func PluginEntryPathGTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldPluginEntryPath, v))
}

// PluginEntryPathLT applies the LT predicate on the "plugin_entry_path" field.
func PluginEntryPathLT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldPluginEntryPath, v))
}

// PluginEntryPathLTE applies the LTE predicate on the "plugin_entry_path" field.
func PluginEntryPathLTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldPluginEntryPath, v))
}

// PluginEntryPathContains applies the Contains predicate on the "plugin_entry_path" field.
func PluginEntryPathContains(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContains(FieldPluginEntryPath, v))
}

// PluginEntryPathHasPrefix applies the HasPrefix predicate on the "plugin_entry_path" field.
func PluginEntryPathHasPrefix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasPrefix(FieldPluginEntryPath, v))
}

// PluginEntryPathHasSuffix applies the HasSuffix predicate on the "plugin_entry_path" field.
func PluginEntryPathHasSuffix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasSuffix(FieldPluginEntryPath, v))
}

// PluginEntryPathEqualFold applies the EqualFold predicate on the "plugin_entry_path" field.
func PluginEntryPathEqualFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEqualFold(FieldPluginEntryPath, v))
}

// PluginEntryPathContainsFold applies the ContainsFold predicate on the "plugin_entry_path" field.
func PluginEntryPathContainsFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContainsFold(FieldPluginEntryPath, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContainsFold(FieldNamespace, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContainsFold(FieldKey, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldContainsFold(FieldValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PluginStorage {
	return predicate.PluginStorage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginStorage) predicate.PluginStorage {
	return predicate.PluginStorage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginStorage) predicate.PluginStorage {
	return predicate.PluginStorage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginStorage) predicate.PluginStorage {
	return predicate.PluginStorage(sql.NotPredicates(p))
}
