// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlbumsColumns holds the columns for the "albums" table.
	AlbumsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "album_artist", Type: field.TypeString, Default: ""},
		{Name: "cover_path", Type: field.TypeString, Default: ""},
		{Name: "favorite", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "artist_albums", Type: field.TypeInt, Nullable: true},
	}
	// AlbumsTable holds the schema information for the "albums" table.
	AlbumsTable = &schema.Table{
		Name:       "albums",
		Columns:    AlbumsColumns,
		PrimaryKey: []*schema.Column{AlbumsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "albums_artists_albums",
				Columns:    []*schema.Column{AlbumsColumns[7]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// ArtistsColumns holds the columns for the "artists" table.
	ArtistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ArtistsTable holds the schema information for the "artists" table.
	ArtistsTable = &schema.Table{
		Name:       "artists",
		Columns:    ArtistsColumns,
		PrimaryKey: []*schema.Column{ArtistsColumns[0]},
	}
	// PlayHistoriesColumns holds the columns for the "play_histories" table.
	PlayHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "played_at", Type: field.TypeTime},
		{Name: "progress_seconds", Type: field.TypeFloat64, Default: 0},
		{Name: "duration_seconds", Type: field.TypeFloat64, Default: 0},
		{Name: "completed", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "song_play_history", Type: field.TypeInt},
		{Name: "user_play_history", Type: field.TypeInt},
	}
	// PlayHistoriesTable holds the schema information for the "play_histories" table.
	PlayHistoriesTable = &schema.Table{
		Name:       "play_histories",
		Columns:    PlayHistoriesColumns,
		PrimaryKey: []*schema.Column{PlayHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "play_histories_songs_play_history",
				Columns:    []*schema.Column{PlayHistoriesColumns[6]},
				RefColumns: []*schema.Column{SongsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "play_histories_users_play_history",
				Columns:    []*schema.Column{PlayHistoriesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "playhistory_user_play_history",
				Unique:  false,
				Columns: []*schema.Column{PlayHistoriesColumns[7]},
			},
			{
				Name:    "playhistory_song_play_history",
				Unique:  false,
				Columns: []*schema.Column{PlayHistoriesColumns[6]},
			},
		},
	}
	// PlaylistsColumns holds the columns for the "playlists" table.
	PlaylistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "cover_theme", Type: field.TypeString, Default: "deep-space"},
		{Name: "favorite", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_playlists", Type: field.TypeInt, Nullable: true},
	}
	// PlaylistsTable holds the schema information for the "playlists" table.
	PlaylistsTable = &schema.Table{
		Name:       "playlists",
		Columns:    PlaylistsColumns,
		PrimaryKey: []*schema.Column{PlaylistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlists_users_playlists",
				Columns:    []*schema.Column{PlaylistsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SongsColumns holds the columns for the "songs" table.
	SongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "file_name", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: ""},
		{Name: "mime", Type: field.TypeString, Default: "application/octet-stream"},
		{Name: "size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "duration_seconds", Type: field.TypeFloat64, Default: 0},
		{Name: "sample_rate", Type: field.TypeInt, Default: 0},
		{Name: "bit_rate", Type: field.TypeInt, Default: 0},
		{Name: "bit_depth", Type: field.TypeInt, Default: 0},
		{Name: "year", Type: field.TypeInt, Default: 0},
		{Name: "lyrics_embedded", Type: field.TypeString, Default: ""},
		{Name: "lyrics_source", Type: field.TypeString, Default: ""},
		{Name: "netease_id", Type: field.TypeString, Default: ""},
		{Name: "favorite", Type: field.TypeBool, Default: false},
		{Name: "play_count", Type: field.TypeInt, Default: 0},
		{Name: "last_played_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "album_songs", Type: field.TypeInt, Nullable: true},
		{Name: "artist_songs", Type: field.TypeInt, Nullable: true},
	}
	// SongsTable holds the schema information for the "songs" table.
	SongsTable = &schema.Table{
		Name:       "songs",
		Columns:    SongsColumns,
		PrimaryKey: []*schema.Column{SongsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "songs_albums_songs",
				Columns:    []*schema.Column{SongsColumns[20]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "songs_artists_songs",
				Columns:    []*schema.Column{SongsColumns[21]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "song_title",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[1]},
			},
			{
				Name:    "song_favorite",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[15]},
			},
			{
				Name:    "song_netease_id",
				Unique:  false,
				Columns: []*schema.Column{SongsColumns[14]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "nickname", Type: field.TypeString, Default: ""},
		{Name: "avatar_data_url", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "mcp_token_hash", Type: field.TypeString, Default: ""},
		{Name: "mcp_token_hint", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserAlbumFavoritesColumns holds the columns for the "user_album_favorites" table.
	UserAlbumFavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "album_user_favorites", Type: field.TypeInt},
		{Name: "user_album_favorites", Type: field.TypeInt},
	}
	// UserAlbumFavoritesTable holds the schema information for the "user_album_favorites" table.
	UserAlbumFavoritesTable = &schema.Table{
		Name:       "user_album_favorites",
		Columns:    UserAlbumFavoritesColumns,
		PrimaryKey: []*schema.Column{UserAlbumFavoritesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_album_favorites_albums_user_favorites",
				Columns:    []*schema.Column{UserAlbumFavoritesColumns[2]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_album_favorites_users_album_favorites",
				Columns:    []*schema.Column{UserAlbumFavoritesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useralbumfavorite_user_album_favorites_album_user_favorites",
				Unique:  true,
				Columns: []*schema.Column{UserAlbumFavoritesColumns[3], UserAlbumFavoritesColumns[2]},
			},
		},
	}
	// UserArtistFavoritesColumns holds the columns for the "user_artist_favorites" table.
	UserArtistFavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "artist_user_favorites", Type: field.TypeInt},
		{Name: "user_artist_favorites", Type: field.TypeInt},
	}
	// UserArtistFavoritesTable holds the schema information for the "user_artist_favorites" table.
	UserArtistFavoritesTable = &schema.Table{
		Name:       "user_artist_favorites",
		Columns:    UserArtistFavoritesColumns,
		PrimaryKey: []*schema.Column{UserArtistFavoritesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_artist_favorites_artists_user_favorites",
				Columns:    []*schema.Column{UserArtistFavoritesColumns[2]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_artist_favorites_users_artist_favorites",
				Columns:    []*schema.Column{UserArtistFavoritesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userartistfavorite_user_artist_favorites_artist_user_favorites",
				Unique:  true,
				Columns: []*schema.Column{UserArtistFavoritesColumns[3], UserArtistFavoritesColumns[2]},
			},
		},
	}
	// UserSongFavoritesColumns holds the columns for the "user_song_favorites" table.
	UserSongFavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "song_user_favorites", Type: field.TypeInt},
		{Name: "user_song_favorites", Type: field.TypeInt},
	}
	// UserSongFavoritesTable holds the schema information for the "user_song_favorites" table.
	UserSongFavoritesTable = &schema.Table{
		Name:       "user_song_favorites",
		Columns:    UserSongFavoritesColumns,
		PrimaryKey: []*schema.Column{UserSongFavoritesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_song_favorites_songs_user_favorites",
				Columns:    []*schema.Column{UserSongFavoritesColumns[2]},
				RefColumns: []*schema.Column{SongsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_song_favorites_users_song_favorites",
				Columns:    []*schema.Column{UserSongFavoritesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usersongfavorite_user_song_favorites_song_user_favorites",
				Unique:  true,
				Columns: []*schema.Column{UserSongFavoritesColumns[3], UserSongFavoritesColumns[2]},
			},
		},
	}
	// PlaylistSongsColumns holds the columns for the "playlist_songs" table.
	PlaylistSongsColumns = []*schema.Column{
		{Name: "playlist_id", Type: field.TypeInt},
		{Name: "song_id", Type: field.TypeInt},
	}
	// PlaylistSongsTable holds the schema information for the "playlist_songs" table.
	PlaylistSongsTable = &schema.Table{
		Name:       "playlist_songs",
		Columns:    PlaylistSongsColumns,
		PrimaryKey: []*schema.Column{PlaylistSongsColumns[0], PlaylistSongsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlist_songs_playlist_id",
				Columns:    []*schema.Column{PlaylistSongsColumns[0]},
				RefColumns: []*schema.Column{PlaylistsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "playlist_songs_song_id",
				Columns:    []*schema.Column{PlaylistSongsColumns[1]},
				RefColumns: []*schema.Column{SongsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlbumsTable,
		AppSettingsTable,
		ArtistsTable,
		PlayHistoriesTable,
		PlaylistsTable,
		SessionsTable,
		SongsTable,
		UsersTable,
		UserAlbumFavoritesTable,
		UserArtistFavoritesTable,
		UserSongFavoritesTable,
		PlaylistSongsTable,
	}
)

func init() {
	AlbumsTable.ForeignKeys[0].RefTable = ArtistsTable
	PlayHistoriesTable.ForeignKeys[0].RefTable = SongsTable
	PlayHistoriesTable.ForeignKeys[1].RefTable = UsersTable
	PlaylistsTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	SongsTable.ForeignKeys[0].RefTable = AlbumsTable
	SongsTable.ForeignKeys[1].RefTable = ArtistsTable
	UserAlbumFavoritesTable.ForeignKeys[0].RefTable = AlbumsTable
	UserAlbumFavoritesTable.ForeignKeys[1].RefTable = UsersTable
	UserArtistFavoritesTable.ForeignKeys[0].RefTable = ArtistsTable
	UserArtistFavoritesTable.ForeignKeys[1].RefTable = UsersTable
	UserSongFavoritesTable.ForeignKeys[0].RefTable = SongsTable
	UserSongFavoritesTable.ForeignKeys[1].RefTable = UsersTable
	PlaylistSongsTable.ForeignKeys[0].RefTable = PlaylistsTable
	PlaylistSongsTable.ForeignKeys[1].RefTable = SongsTable
}
