// Code generated by ent, DO NOT EDIT.

package playlistsongposition

import (
	"lark/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLTE(FieldID, id))
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldPlaylistID, v))
}

// SongID applies equality check predicate on the "song_id" field. It's identical to SongIDEQ.
func SongID(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldSongID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldPosition, v))
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNEQ(FieldPlaylistID, v))
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldIn(FieldPlaylistID, vs...))
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNotIn(FieldPlaylistID, vs...))
}

// PlaylistIDGT applies the GT predicate on the "playlist_id" field.
func PlaylistIDGT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGT(FieldPlaylistID, v))
}

// PlaylistIDGTE applies the GTE predicate on the "playlist_id" field.
func PlaylistIDGTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGTE(FieldPlaylistID, v))
}

// PlaylistIDLT applies the LT predicate on the "playlist_id" field.
func PlaylistIDLT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLT(FieldPlaylistID, v))
}

// PlaylistIDLTE applies the LTE predicate on the "playlist_id" field.
func PlaylistIDLTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLTE(FieldPlaylistID, v))
}

// SongIDEQ applies the EQ predicate on the "song_id" field.
func SongIDEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldSongID, v))
}

// SongIDNEQ applies the NEQ predicate on the "song_id" field.
func SongIDNEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNEQ(FieldSongID, v))
}

// SongIDIn applies the In predicate on the "song_id" field.
func SongIDIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldIn(FieldSongID, vs...))
}

// SongIDNotIn applies the NotIn predicate on the "song_id" field.
func SongIDNotIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNotIn(FieldSongID, vs...))
}

// SongIDGT applies the GT predicate on the "song_id" field.
func SongIDGT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGT(FieldSongID, v))
}

// SongIDGTE applies the GTE predicate on the "song_id" field.
func SongIDGTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGTE(FieldSongID, v))
}

// SongIDLT applies the LT predicate on the "song_id" field.
func SongIDLT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLT(FieldSongID, v))
}

// SongIDLTE applies the LTE predicate on the "song_id" field.
func SongIDLTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLTE(FieldSongID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.FieldLTE(FieldPosition, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlaylistSongPosition) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlaylistSongPosition) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaylistSongPosition) predicate.PlaylistSongPosition {
	return predicate.PlaylistSongPosition(sql.NotPredicates(p))
}
