// Code generated by ent, DO NOT EDIT.

package playhistory

import (
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldID, id))
}

// PlayedAt applies equality check predicate on the "played_at" field. It's identical to PlayedAtEQ.
func PlayedAt(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldPlayedAt, v))
}

// ProgressSeconds applies equality check predicate on the "progress_seconds" field. It's identical to ProgressSecondsEQ.
func ProgressSeconds(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldProgressSeconds, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldDurationSeconds, v))
}

// Completed applies equality check predicate on the "completed" field. It's identical to CompletedEQ.
func Completed(v bool) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldCompleted, v))
}

// DeviceType applies equality check predicate on the "device_type" field. It's identical to DeviceTypeEQ.
func DeviceType(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldDeviceType, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlayedAtEQ applies the EQ predicate on the "played_at" field.
func PlayedAtEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldPlayedAt, v))
}

// PlayedAtNEQ applies the NEQ predicate on the "played_at" field.
func PlayedAtNEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldPlayedAt, v))
}

// PlayedAtIn applies the In predicate on the "played_at" field.
func PlayedAtIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldPlayedAt, vs...))
}

// PlayedAtNotIn applies the NotIn predicate on the "played_at" field.
func PlayedAtNotIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldPlayedAt, vs...))
}

// PlayedAtGT applies the GT predicate on the "played_at" field.
func PlayedAtGT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldPlayedAt, v))
}

// PlayedAtGTE applies the GTE predicate on the "played_at" field.
func PlayedAtGTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldPlayedAt, v))
}

// PlayedAtLT applies the LT predicate on the "played_at" field.
func PlayedAtLT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldPlayedAt, v))
}

// PlayedAtLTE applies the LTE predicate on the "played_at" field.
func PlayedAtLTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldPlayedAt, v))
}

// ProgressSecondsEQ applies the EQ predicate on the "progress_seconds" field.
func ProgressSecondsEQ(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldProgressSeconds, v))
}

// ProgressSecondsNEQ applies the NEQ predicate on the "progress_seconds" field.
func ProgressSecondsNEQ(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldProgressSeconds, v))
}

// ProgressSecondsIn applies the In predicate on the "progress_seconds" field.
func ProgressSecondsIn(vs ...float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldProgressSeconds, vs...))
}

// ProgressSecondsNotIn applies the NotIn predicate on the "progress_seconds" field.
func ProgressSecondsNotIn(vs ...float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldProgressSeconds, vs...))
}

// ProgressSecondsGT applies the GT predicate on the "progress_seconds" field.
func ProgressSecondsGT(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldProgressSeconds, v))
}

// ProgressSecondsGTE applies the GTE predicate on the "progress_seconds" field.
func ProgressSecondsGTE(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldProgressSeconds, v))
}

// ProgressSecondsLT applies the LT predicate on the "progress_seconds" field.
func ProgressSecondsLT(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldProgressSeconds, v))
}

// ProgressSecondsLTE applies the LTE predicate on the "progress_seconds" field.
func ProgressSecondsLTE(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldProgressSeconds, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v float64) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldDurationSeconds, v))
}

// CompletedEQ applies the EQ predicate on the "completed" field.
func CompletedEQ(v bool) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldCompleted, v))
}

// CompletedNEQ applies the NEQ predicate on the "completed" field.
func CompletedNEQ(v bool) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldCompleted, v))
}

// DeviceTypeEQ applies the EQ predicate on the "device_type" field.
func DeviceTypeEQ(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldDeviceType, v))
}

// DeviceTypeNEQ applies the NEQ predicate on the "device_type" field.
func DeviceTypeNEQ(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldDeviceType, v))
}

// DeviceTypeIn applies the In predicate on the "device_type" field.
func DeviceTypeIn(vs ...string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldDeviceType, vs...))
}

// DeviceTypeNotIn applies the NotIn predicate on the "device_type" field.
func DeviceTypeNotIn(vs ...string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldDeviceType, vs...))
}

// DeviceTypeGT applies the GT predicate on the "device_type" field.
func DeviceTypeGT(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldDeviceType, v))
}

// DeviceTypeGTE applies the GTE predicate on the "device_type" field.
func DeviceTypeGTE(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldDeviceType, v))
}

// DeviceTypeLT applies the LT predicate on the "device_type" field.
func DeviceTypeLT(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldDeviceType, v))
}

// DeviceTypeLTE applies the LTE predicate on the "device_type" field.
func DeviceTypeLTE(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldDeviceType, v))
}

// DeviceTypeContains applies the Contains predicate on the "device_type" field.
func DeviceTypeContains(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldContains(FieldDeviceType, v))
}

// DeviceTypeHasPrefix applies the HasPrefix predicate on the "device_type" field.
func DeviceTypeHasPrefix(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldHasPrefix(FieldDeviceType, v))
}

// DeviceTypeHasSuffix applies the HasSuffix predicate on the "device_type" field.
func DeviceTypeHasSuffix(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldHasSuffix(FieldDeviceType, v))
}

// DeviceTypeEqualFold applies the EqualFold predicate on the "device_type" field.
func DeviceTypeEqualFold(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEqualFold(FieldDeviceType, v))
}

// DeviceTypeContainsFold applies the ContainsFold predicate on the "device_type" field.
func DeviceTypeContainsFold(v string) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldContainsFold(FieldDeviceType, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSong applies the HasEdge predicate on the "song" edge.
func HasSong() predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSongWith applies the HasEdge predicate on the "song" edge with a given conditions (other predicates).
func HasSongWith(preds ...predicate.Song) predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := newSongStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.NotPredicates(p))
}
