// Code generated by ent, DO NOT EDIT.

package playhistory

import (
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldID, id))
}

// PlayedAt applies equality check predicate on the "played_at" field. It's identical to PlayedAtEQ.
func PlayedAt(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldPlayedAt, v))
}

// PlayedAtEQ applies the EQ predicate on the "played_at" field.
func PlayedAtEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldEQ(FieldPlayedAt, v))
}

// PlayedAtNEQ applies the NEQ predicate on the "played_at" field.
func PlayedAtNEQ(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNEQ(FieldPlayedAt, v))
}

// PlayedAtIn applies the In predicate on the "played_at" field.
func PlayedAtIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldIn(FieldPlayedAt, vs...))
}

// PlayedAtNotIn applies the NotIn predicate on the "played_at" field.
func PlayedAtNotIn(vs ...time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldNotIn(FieldPlayedAt, vs...))
}

// PlayedAtGT applies the GT predicate on the "played_at" field.
func PlayedAtGT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGT(FieldPlayedAt, v))
}

// PlayedAtGTE applies the GTE predicate on the "played_at" field.
func PlayedAtGTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldGTE(FieldPlayedAt, v))
}

// PlayedAtLT applies the LT predicate on the "played_at" field.
func PlayedAtLT(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLT(FieldPlayedAt, v))
}

// PlayedAtLTE applies the LTE predicate on the "played_at" field.
func PlayedAtLTE(v time.Time) predicate.PlayHistory {
	return predicate.PlayHistory(sql.FieldLTE(FieldPlayedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSong applies the HasEdge predicate on the "song" edge.
func HasSong() predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSongWith applies the HasEdge predicate on the "song" edge with a given conditions (other predicates).
func HasSongWith(preds ...predicate.Song) predicate.PlayHistory {
	return predicate.PlayHistory(func(s *sql.Selector) {
		step := newSongStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayHistory) predicate.PlayHistory {
	return predicate.PlayHistory(sql.NotPredicates(p))
}
