// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAuthor, v))
}

// Homepage applies equality check predicate on the "homepage" field. It's identical to HomepageEQ.
func Homepage(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldHomepage, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLicense, v))
}

// EntryPath applies equality check predicate on the "entry_path" field. It's identical to EntryPathEQ.
func EntryPath(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEntryPath, v))
}

// Main applies equality check predicate on the "main" field. It's identical to MainEQ.
func Main(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMain, v))
}

// MinHostVersion applies equality check predicate on the "min_host_version" field. It's identical to MinHostVersionEQ.
func MinHostVersion(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMinHostVersion, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIcon, v))
}

// UpdateURL applies equality check predicate on the "update_url" field. It's identical to UpdateURLEQ.
func UpdateURL(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdateURL, v))
}

// DownloadURL applies equality check predicate on the "download_url" field. It's identical to DownloadURLEQ.
func DownloadURL(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDownloadURL, v))
}

// RenderEngine applies equality check predicate on the "render_engine" field. It's identical to RenderEngineEQ.
func RenderEngine(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldRenderEngine, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatus, v))
}

// ZipHash applies equality check predicate on the "zip_hash" field. It's identical to ZipHashEQ.
func ZipHash(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldZipHash, v))
}

// EntryHash applies equality check predicate on the "entry_hash" field. It's identical to EntryHashEQ.
func EntryHash(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEntryHash, v))
}

// FileModTime applies equality check predicate on the "file_mod_time" field. It's identical to FileModTimeEQ.
func FileModTime(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldFileModTime, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldFilePath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldVersion, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDescription, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldAuthor, v))
}

// HomepageEQ applies the EQ predicate on the "homepage" field.
func HomepageEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldHomepage, v))
}

// HomepageNEQ applies the NEQ predicate on the "homepage" field.
func HomepageNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldHomepage, v))
}

// HomepageIn applies the In predicate on the "homepage" field.
func HomepageIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldHomepage, vs...))
}

// HomepageNotIn applies the NotIn predicate on the "homepage" field.
func HomepageNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldHomepage, vs...))
}

// HomepageGT applies the GT predicate on the "homepage" field.
func HomepageGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldHomepage, v))
}

// HomepageGTE applies the GTE predicate on the "homepage" field.
func HomepageGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldHomepage, v))
}

// HomepageLT applies the LT predicate on the "homepage" field.
func HomepageLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldHomepage, v))
}

// HomepageLTE applies the LTE predicate on the "homepage" field.
func HomepageLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldHomepage, v))
}

// HomepageContains applies the Contains predicate on the "homepage" field.
func HomepageContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldHomepage, v))
}

// HomepageHasPrefix applies the HasPrefix predicate on the "homepage" field.
func HomepageHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldHomepage, v))
}

// HomepageHasSuffix applies the HasSuffix predicate on the "homepage" field.
func HomepageHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldHomepage, v))
}

// HomepageEqualFold applies the EqualFold predicate on the "homepage" field.
func HomepageEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldHomepage, v))
}

// HomepageContainsFold applies the ContainsFold predicate on the "homepage" field.
func HomepageContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldHomepage, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldLicense, v))
}

// EntryPathEQ applies the EQ predicate on the "entry_path" field.
func EntryPathEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEntryPath, v))
}

// EntryPathNEQ applies the NEQ predicate on the "entry_path" field.
func EntryPathNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldEntryPath, v))
}

// EntryPathIn applies the In predicate on the "entry_path" field.
func EntryPathIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldEntryPath, vs...))
}

// EntryPathNotIn applies the NotIn predicate on the "entry_path" field.
func EntryPathNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldEntryPath, vs...))
}

// EntryPathGT applies the GT predicate on the "entry_path" field.
func EntryPathGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldEntryPath, v))
}

// EntryPathGTE applies the GTE predicate on the "entry_path" field.
func EntryPathGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldEntryPath, v))
}

// EntryPathLT applies the LT predicate on the "entry_path" field.
func EntryPathLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldEntryPath, v))
}

// EntryPathLTE applies the LTE predicate on the "entry_path" field.
func EntryPathLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldEntryPath, v))
}

// EntryPathContains applies the Contains predicate on the "entry_path" field.
func EntryPathContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldEntryPath, v))
}

// EntryPathHasPrefix applies the HasPrefix predicate on the "entry_path" field.
func EntryPathHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldEntryPath, v))
}

// EntryPathHasSuffix applies the HasSuffix predicate on the "entry_path" field.
func EntryPathHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldEntryPath, v))
}

// EntryPathEqualFold applies the EqualFold predicate on the "entry_path" field.
func EntryPathEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldEntryPath, v))
}

// EntryPathContainsFold applies the ContainsFold predicate on the "entry_path" field.
func EntryPathContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldEntryPath, v))
}

// MainEQ applies the EQ predicate on the "main" field.
func MainEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMain, v))
}

// MainNEQ applies the NEQ predicate on the "main" field.
func MainNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldMain, v))
}

// MainIn applies the In predicate on the "main" field.
func MainIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldMain, vs...))
}

// MainNotIn applies the NotIn predicate on the "main" field.
func MainNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldMain, vs...))
}

// MainGT applies the GT predicate on the "main" field.
func MainGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldMain, v))
}

// MainGTE applies the GTE predicate on the "main" field.
func MainGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldMain, v))
}

// MainLT applies the LT predicate on the "main" field.
func MainLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldMain, v))
}

// MainLTE applies the LTE predicate on the "main" field.
func MainLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldMain, v))
}

// MainContains applies the Contains predicate on the "main" field.
func MainContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldMain, v))
}

// MainHasPrefix applies the HasPrefix predicate on the "main" field.
func MainHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldMain, v))
}

// MainHasSuffix applies the HasSuffix predicate on the "main" field.
func MainHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldMain, v))
}

// MainEqualFold applies the EqualFold predicate on the "main" field.
func MainEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldMain, v))
}

// MainContainsFold applies the ContainsFold predicate on the "main" field.
func MainContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldMain, v))
}

// MinHostVersionEQ applies the EQ predicate on the "min_host_version" field.
func MinHostVersionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMinHostVersion, v))
}

// MinHostVersionNEQ applies the NEQ predicate on the "min_host_version" field.
func MinHostVersionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldMinHostVersion, v))
}

// MinHostVersionIn applies the In predicate on the "min_host_version" field.
func MinHostVersionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldMinHostVersion, vs...))
}

// MinHostVersionNotIn applies the NotIn predicate on the "min_host_version" field.
func MinHostVersionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldMinHostVersion, vs...))
}

// MinHostVersionGT applies the GT predicate on the "min_host_version" field.
func MinHostVersionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldMinHostVersion, v))
}

// MinHostVersionGTE applies the GTE predicate on the "min_host_version" field.
func MinHostVersionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldMinHostVersion, v))
}

// MinHostVersionLT applies the LT predicate on the "min_host_version" field.
func MinHostVersionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldMinHostVersion, v))
}

// MinHostVersionLTE applies the LTE predicate on the "min_host_version" field.
func MinHostVersionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldMinHostVersion, v))
}

// MinHostVersionContains applies the Contains predicate on the "min_host_version" field.
func MinHostVersionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldMinHostVersion, v))
}

// MinHostVersionHasPrefix applies the HasPrefix predicate on the "min_host_version" field.
func MinHostVersionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldMinHostVersion, v))
}

// MinHostVersionHasSuffix applies the HasSuffix predicate on the "min_host_version" field.
func MinHostVersionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldMinHostVersion, v))
}

// MinHostVersionEqualFold applies the EqualFold predicate on the "min_host_version" field.
func MinHostVersionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldMinHostVersion, v))
}

// MinHostVersionContainsFold applies the ContainsFold predicate on the "min_host_version" field.
func MinHostVersionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldMinHostVersion, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldIcon, v))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldIcon, v))
}

// UpdateURLEQ applies the EQ predicate on the "update_url" field.
func UpdateURLEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdateURL, v))
}

// UpdateURLNEQ applies the NEQ predicate on the "update_url" field.
func UpdateURLNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldUpdateURL, v))
}

// UpdateURLIn applies the In predicate on the "update_url" field.
func UpdateURLIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldUpdateURL, vs...))
}

// UpdateURLNotIn applies the NotIn predicate on the "update_url" field.
func UpdateURLNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldUpdateURL, vs...))
}

// UpdateURLGT applies the GT predicate on the "update_url" field.
func UpdateURLGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldUpdateURL, v))
}

// UpdateURLGTE applies the GTE predicate on the "update_url" field.
func UpdateURLGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldUpdateURL, v))
}

// UpdateURLLT applies the LT predicate on the "update_url" field.
func UpdateURLLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldUpdateURL, v))
}

// UpdateURLLTE applies the LTE predicate on the "update_url" field.
func UpdateURLLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldUpdateURL, v))
}

// UpdateURLContains applies the Contains predicate on the "update_url" field.
func UpdateURLContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldUpdateURL, v))
}

// UpdateURLHasPrefix applies the HasPrefix predicate on the "update_url" field.
func UpdateURLHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldUpdateURL, v))
}

// UpdateURLHasSuffix applies the HasSuffix predicate on the "update_url" field.
func UpdateURLHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldUpdateURL, v))
}

// UpdateURLEqualFold applies the EqualFold predicate on the "update_url" field.
func UpdateURLEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldUpdateURL, v))
}

// UpdateURLContainsFold applies the ContainsFold predicate on the "update_url" field.
func UpdateURLContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldUpdateURL, v))
}

// DownloadURLEQ applies the EQ predicate on the "download_url" field.
func DownloadURLEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDownloadURL, v))
}

// DownloadURLNEQ applies the NEQ predicate on the "download_url" field.
func DownloadURLNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDownloadURL, v))
}

// DownloadURLIn applies the In predicate on the "download_url" field.
func DownloadURLIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDownloadURL, vs...))
}

// DownloadURLNotIn applies the NotIn predicate on the "download_url" field.
func DownloadURLNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDownloadURL, vs...))
}

// DownloadURLGT applies the GT predicate on the "download_url" field.
func DownloadURLGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDownloadURL, v))
}

// DownloadURLGTE applies the GTE predicate on the "download_url" field.
func DownloadURLGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDownloadURL, v))
}

// DownloadURLLT applies the LT predicate on the "download_url" field.
func DownloadURLLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDownloadURL, v))
}

// DownloadURLLTE applies the LTE predicate on the "download_url" field.
func DownloadURLLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDownloadURL, v))
}

// DownloadURLContains applies the Contains predicate on the "download_url" field.
func DownloadURLContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDownloadURL, v))
}

// DownloadURLHasPrefix applies the HasPrefix predicate on the "download_url" field.
func DownloadURLHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDownloadURL, v))
}

// DownloadURLHasSuffix applies the HasSuffix predicate on the "download_url" field.
func DownloadURLHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDownloadURL, v))
}

// DownloadURLEqualFold applies the EqualFold predicate on the "download_url" field.
func DownloadURLEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDownloadURL, v))
}

// DownloadURLContainsFold applies the ContainsFold predicate on the "download_url" field.
func DownloadURLContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDownloadURL, v))
}

// RenderEngineEQ applies the EQ predicate on the "render_engine" field.
func RenderEngineEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldRenderEngine, v))
}

// RenderEngineNEQ applies the NEQ predicate on the "render_engine" field.
func RenderEngineNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldRenderEngine, v))
}

// RenderEngineIn applies the In predicate on the "render_engine" field.
func RenderEngineIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldRenderEngine, vs...))
}

// RenderEngineNotIn applies the NotIn predicate on the "render_engine" field.
func RenderEngineNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldRenderEngine, vs...))
}

// RenderEngineGT applies the GT predicate on the "render_engine" field.
func RenderEngineGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldRenderEngine, v))
}

// RenderEngineGTE applies the GTE predicate on the "render_engine" field.
func RenderEngineGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldRenderEngine, v))
}

// RenderEngineLT applies the LT predicate on the "render_engine" field.
func RenderEngineLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldRenderEngine, v))
}

// RenderEngineLTE applies the LTE predicate on the "render_engine" field.
func RenderEngineLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldRenderEngine, v))
}

// RenderEngineContains applies the Contains predicate on the "render_engine" field.
func RenderEngineContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldRenderEngine, v))
}

// RenderEngineHasPrefix applies the HasPrefix predicate on the "render_engine" field.
func RenderEngineHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldRenderEngine, v))
}

// RenderEngineHasSuffix applies the HasSuffix predicate on the "render_engine" field.
func RenderEngineHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldRenderEngine, v))
}

// RenderEngineEqualFold applies the EqualFold predicate on the "render_engine" field.
func RenderEngineEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldRenderEngine, v))
}

// RenderEngineContainsFold applies the ContainsFold predicate on the "render_engine" field.
func RenderEngineContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldRenderEngine, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldStatus, v))
}

// ZipHashEQ applies the EQ predicate on the "zip_hash" field.
func ZipHashEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldZipHash, v))
}

// ZipHashNEQ applies the NEQ predicate on the "zip_hash" field.
func ZipHashNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldZipHash, v))
}

// ZipHashIn applies the In predicate on the "zip_hash" field.
func ZipHashIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldZipHash, vs...))
}

// ZipHashNotIn applies the NotIn predicate on the "zip_hash" field.
func ZipHashNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldZipHash, vs...))
}

// ZipHashGT applies the GT predicate on the "zip_hash" field.
func ZipHashGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldZipHash, v))
}

// ZipHashGTE applies the GTE predicate on the "zip_hash" field.
func ZipHashGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldZipHash, v))
}

// ZipHashLT applies the LT predicate on the "zip_hash" field.
func ZipHashLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldZipHash, v))
}

// ZipHashLTE applies the LTE predicate on the "zip_hash" field.
func ZipHashLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldZipHash, v))
}

// ZipHashContains applies the Contains predicate on the "zip_hash" field.
func ZipHashContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldZipHash, v))
}

// ZipHashHasPrefix applies the HasPrefix predicate on the "zip_hash" field.
func ZipHashHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldZipHash, v))
}

// ZipHashHasSuffix applies the HasSuffix predicate on the "zip_hash" field.
func ZipHashHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldZipHash, v))
}

// ZipHashEqualFold applies the EqualFold predicate on the "zip_hash" field.
func ZipHashEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldZipHash, v))
}

// ZipHashContainsFold applies the ContainsFold predicate on the "zip_hash" field.
func ZipHashContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldZipHash, v))
}

// EntryHashEQ applies the EQ predicate on the "entry_hash" field.
func EntryHashEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEntryHash, v))
}

// EntryHashNEQ applies the NEQ predicate on the "entry_hash" field.
func EntryHashNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldEntryHash, v))
}

// EntryHashIn applies the In predicate on the "entry_hash" field.
func EntryHashIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldEntryHash, vs...))
}

// EntryHashNotIn applies the NotIn predicate on the "entry_hash" field.
func EntryHashNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldEntryHash, vs...))
}

// EntryHashGT applies the GT predicate on the "entry_hash" field.
func EntryHashGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldEntryHash, v))
}

// EntryHashGTE applies the GTE predicate on the "entry_hash" field.
func EntryHashGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldEntryHash, v))
}

// EntryHashLT applies the LT predicate on the "entry_hash" field.
func EntryHashLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldEntryHash, v))
}

// EntryHashLTE applies the LTE predicate on the "entry_hash" field.
func EntryHashLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldEntryHash, v))
}

// EntryHashContains applies the Contains predicate on the "entry_hash" field.
func EntryHashContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldEntryHash, v))
}

// EntryHashHasPrefix applies the HasPrefix predicate on the "entry_hash" field.
func EntryHashHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldEntryHash, v))
}

// EntryHashHasSuffix applies the HasSuffix predicate on the "entry_hash" field.
func EntryHashHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldEntryHash, v))
}

// EntryHashEqualFold applies the EqualFold predicate on the "entry_hash" field.
func EntryHashEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldEntryHash, v))
}

// EntryHashContainsFold applies the ContainsFold predicate on the "entry_hash" field.
func EntryHashContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldEntryHash, v))
}

// FileModTimeEQ applies the EQ predicate on the "file_mod_time" field.
func FileModTimeEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldFileModTime, v))
}

// FileModTimeNEQ applies the NEQ predicate on the "file_mod_time" field.
func FileModTimeNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldFileModTime, v))
}

// FileModTimeIn applies the In predicate on the "file_mod_time" field.
func FileModTimeIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldFileModTime, vs...))
}

// FileModTimeNotIn applies the NotIn predicate on the "file_mod_time" field.
func FileModTimeNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldFileModTime, vs...))
}

// FileModTimeGT applies the GT predicate on the "file_mod_time" field.
func FileModTimeGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldFileModTime, v))
}

// FileModTimeGTE applies the GTE predicate on the "file_mod_time" field.
func FileModTimeGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldFileModTime, v))
}

// FileModTimeLT applies the LT predicate on the "file_mod_time" field.
func FileModTimeLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldFileModTime, v))
}

// FileModTimeLTE applies the LTE predicate on the "file_mod_time" field.
func FileModTimeLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldFileModTime, v))
}

// FileModTimeContains applies the Contains predicate on the "file_mod_time" field.
func FileModTimeContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldFileModTime, v))
}

// FileModTimeHasPrefix applies the HasPrefix predicate on the "file_mod_time" field.
func FileModTimeHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldFileModTime, v))
}

// FileModTimeHasSuffix applies the HasSuffix predicate on the "file_mod_time" field.
func FileModTimeHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldFileModTime, v))
}

// FileModTimeEqualFold applies the EqualFold predicate on the "file_mod_time" field.
func FileModTimeEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldFileModTime, v))
}

// FileModTimeContainsFold applies the ContainsFold predicate on the "file_mod_time" field.
func FileModTimeContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldFileModTime, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldFilePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.NotPredicates(p))
}
