// Code generated by ent, DO NOT EDIT.

package librarydirectory

import (
	"lark/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLTE(FieldID, id))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldPath, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldNote, v))
}

// WatchEnabled applies equality check predicate on the "watch_enabled" field. It's identical to WatchEnabledEQ.
func WatchEnabled(v bool) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldWatchEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldUpdatedAt, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldContainsFold(FieldPath, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldContainsFold(FieldNote, v))
}

// WatchEnabledEQ applies the EQ predicate on the "watch_enabled" field.
func WatchEnabledEQ(v bool) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldWatchEnabled, v))
}

// WatchEnabledNEQ applies the NEQ predicate on the "watch_enabled" field.
func WatchEnabledNEQ(v bool) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldWatchEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LibraryDirectory {
	return predicate.LibraryDirectory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LibraryDirectory) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LibraryDirectory) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LibraryDirectory) predicate.LibraryDirectory {
	return predicate.LibraryDirectory(sql.NotPredicates(p))
}
